Repository inception-project/inception, pull requests merged in 2019-05, with the labels that each got.

#1138 #1137 Learning curve is not shown on annotation page
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/LearningCurveChartPanel.java
Labels: Module: Recommender, 🐛Bug

#1092 Bugfix/140 no statements with reification enabled
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBQualifier.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBStatement.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/reification/NoReification.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/reification/ReificationStrategy.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/reification/WikiDataReification.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplQualifierIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseSubPropertyLabelTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/reification/WikiDataReificationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/SubclassCreationDialog.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/PropertyFeatureEditor.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/QualifierEditor.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementEditor.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.java
Labels: Module: Knowledge Base, Needs Review, 🐛Bug

#1156 #1155 - Upgrade to DL4J 1.0.0-beta4
  inception-imls-dl4j/pom.xml
  inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
  pom.xml
Labels: Module: Recommender, ⚙️Refactoring

#1141 #1069 - RefactorUncertaintySamplingStrategy
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningService.java
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/strategy/ActiveLearningStrategy.java
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/strategy/UncertaintySamplingStrategy.java
Labels: Module: Active Learning, Needs Review, ⚙️Refactoring

#1148 #1147 - Errors logged when indexing large annotations
  inception-search-core/src/main/resources/META-INF/asciidoc/user-guide/search-core.adoc
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
Labels: Module: Project Search, 🐛Bug

#1077 #1076 - Entity candidate ranking too biased towards query or mention similarity
  inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java
Labels: Module: Entity Linking, Needs Review, 🆕Enhancement

#1154 #1153 - CSS3 animated fade for menu item highlights
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/css/inception.css
  inception-ui-core/pom.xml
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/DashboardMenu.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/DashboardMenu.java
Labels: Module: Dashboard, ⚙️Refactoring, 🕶️UX

#1158 #808 Project Settings Panel for Simulated Evaluation
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/chart/ChartPanel.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/chart/resources/chart.js
Labels: Module: Recommender, 🐛Bug

#1139 #1127 Improve Permanent AnnotationPage Error messages
  inception-recommendation/pom.xml
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
Labels: Module: Annotation, 🆕Enhancement, 🕶️UX

#1161 #768 - Delete outdated modules
  inception-app-webapp/pom.xml
  inception-imls-mira/LICENSE.txt
  inception-imls-mira/pom.xml
  inception-imls-mira/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/BaseConfiguration.java
  inception-imls-mira/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/IncrementalMira.java
  inception-imls-mira/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/MiraConfigurationParameters.java
  inception-imls-mira/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/MiraPosClassificationTool.java
  inception-imls-mira/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/MiraPosClassificationToolFactory.java
  inception-imls-mira/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/MiraPosClassifier.java
  inception-imls-mira/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/MiraPosTrainer.java
  inception-imls-mira/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/TestMira.java
  inception-imls-mira/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/mira/pos/MiraPosClassificationToolTest.java
  inception-search-mimir/pom.xml
  inception-search-mimir/src/main/java/de/tudarmstadt/ukp/inception/search/index/mimir/DKPro2Gate.java
  inception-search-mimir/src/main/java/de/tudarmstadt/ukp/inception/search/index/mimir/MimirDocumentIndex.java
  inception-search-mimir/src/main/java/de/tudarmstadt/ukp/inception/search/index/mimir/MimirDocumentIndexFactory.java
  inception-search-mimir/src/test/java/de/tudarmstadt/ukp/inception/search/index/mimir/TestMimir.java
  inception-search-mimir/src/test/resources/gate/DefaultTokeniser.rules
  inception-search-mimir/src/test/resources/log4j2.xml
  inception-search-mimir/src/test/resources/texts/ner2002_test.conll
  inception-search-solr/LICENSE.txt
  pom.xml
Labels: Module: Project Search, Module: Recommender, ⚙️Refactoring

#1163 #1162 - Update checkstyle maven plugin
  pom.xml
Labels: Needs Review, ⚙️Refactoring

#1165 #1164 - Display image of image features in popover
  inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureSupport.java
Labels: Module: Images, 🆕Enhancement, 🕶️UX

#1166 #310 - Always show description of linked concept in popover
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBInstance.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBObject.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
Labels: Module: Annotation, Module: Entity Linking, Module: Knowledge Base, Needs Review, 🆕Enhancement

#1171 #1170 - Concept value editor on KB page tries all KBs
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.java
Labels: Module: Knowledge Base, 🐛Bug

#1167 #1136 - Qualifiers editable for read-only KBs
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/QualifierEditor.java
Labels: Module: Knowledge Base, 🐛Bug

#1152 #1151 Update Wine KB with labels
  inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/pre-defined-knowledge-bases/wine.rdf
  inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/knowledge_base.adoc
Labels: Module: Knowledge Base, 🆕Enhancement

#1150 #1149 - KB profile file needs to be updated and cleaned up
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
  inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
  inception-kb/src/test/resources/data/README.txt
  inception-kb/src/test/resources/data/wordnet-ontolex-ontology.owl
  inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/projects_knowledge-base.adoc
Labels: Module: Knowledge Base, 🆕Enhancement

#1145 #1144 - Import of logged events very slow
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
Labels: Needs Review, ⚙️Refactoring, 🚀Performance

#1175 #1126 - PubAnnotation Import Exception
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java
Labels: Module: PubAnnotation, 🐛Bug

#1179 #1178 - Allow OpenNLP POS tagger for concept features
  inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderFactory.java
  inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderFactory.java
Labels: Module: Recommender, 🆕Enhancement

#1188 #1187 - Upgrade dependencies
  pom.xml
Labels: ⚙️Refactoring

#1192 #1191 - Fix link to docker compose
  inception-app-webapp/src/main/docker/README.md
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose.yml
Labels: 🐛Bug, 📖Documentation

#1193 #1187 - Upgrade dependencies
  pom.xml
Labels: Module: Knowledge Base, Requires upstream changes, 🐛Bug

#1190 #1173 - Exception when linked entity spans lines
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
  inception-kb/src/test/resources/upstream-data/1.1.ttl
  inception-kb/src/test/resources/upstream-data/README.txt
  inception-kb/src/test/resources/upstream-data/penn.owl
Labels: Module: Entity Linking, Module: Knowledge Base, 🐛Bug

#1195 #1185 - Can't export Weblicht TCF
  pom.xml
Labels: Requires upstream changes, 🐛Bug

#1198 Fix filename of the MySQL client conf
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mysql.adoc
Labels: 🐛Bug, 📖Documentation

#1202 #1201 - Support reading TEI format
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/TeiFormatSupport.java
Labels: 🆕Enhancement

#1210 #1208 - No recommendations if document title doesn't match file name
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
Labels: Module: Recommender, Requires upstream changes, 🐛Bug

#1220 #1219 - Description tooltips not showing for feature labels
  inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureEditor.html
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
Labels: Module: Images, Module: Knowledge Base, 🐛Bug

#1224 #1223 - Support reading the XML format for the Perseus treebank
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/PerseusFormatSupport.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/PerseusReader.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/perseus/internal/model/PerseusSentence.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/perseus/internal/model/PerseusWord.java
  pom.xml
Labels: 🆕Enhancement

#1221 Fix random search for java api
  inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java
Labels: Module: External Search, 🆕Enhancement
