Repository inception-project/inception, pull requests merged in 2019-11, with the labels that each got.

#1500 #1498 - Active learning complains about not serializable confidence explanation
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java
Labels: Module: Active Learning, Module: Recommender, 🐛Bug

#1494 #1456 - Upgrade dependencies
  .mvn/jvm.config
  inception-app-webapp/pom.xml
  inception-build/src/main/resources/inception/checkstyle.xml
  inception-concept-linking/pom.xml
  inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/service/SpringConfig.java
  inception-pdf-editor/pom.xml
  inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  pom.xml
Labels: ⚙️Refactoring

#1431 Bugfix/#1430 catch exception instead of throwable
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/PDFExtractor.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/TaskConsumer.java
Labels: ⚙️Refactoring

#1504 #1456 - Upgrade dependencies
  inception-build/src/main/resources/inception/checkstyle.xml
  pom.xml
Labels: ⚙️Refactoring

#1499 #1211 - Only predict on all documents when in Active Learning Mode
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception-recommendation-api/pom.xml
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Preferences.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
  inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java
  pom.xml
Labels: Module: Active Learning, Module: Recommender, Scalability, 🆕Enhancement

#1506 #1505 - PDF (PDFAnno) Editor not shows up in Settings
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditorFactory.java
Labels: Module: PDF editor, 🐛Bug

#1509 #1508 - Support character-level external recommenders
  inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderFactory.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
Labels: Module: Recommender, 🆕Enhancement

#1523 #1522 - GND tests not running
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseSubPropertyLabelTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
Labels: ⚙️Refactoring

#1515 #1041 - add possibility of defining keyboard shortcuts
  inception-doc/src/main/resources/META-INF/asciidoc/developer-guide.adoc
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureTraits.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.html
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.java
  inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java
Labels: 🆕Enhancement, 🕶️UX

#1525 #1524 - Cannot find sentence for mention
  inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
Labels: Module: Entity Linking, 🐛Bug

#1526 #1513 - PDF editor crashes when clicking on recommendation
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
Labels: Module: PDF editor, 🐛Bug

#1530 #1528 - Reduce database accesses during recommendation rendering
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
Labels: Module: Recommender, ⚙️Refactoring

#1532 #1484 - make tooltip for KB instance URI clickable
  inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
Labels: Module: Entity Linking, 🆕Enhancement

#1529 #1527 - Batch event log writes
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
Labels: Module: Logging, ⚙️Refactoring

#1521 #1518 Document where the settings.properties file lives
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_home.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings.adoc
  inception-layer-docmetadata/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_docmeta.adoc
Labels: Needs Review, 📖Documentation

#1472 Refactor/#1434 Remove the useless curly braces
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplQualifierIntegrationTest.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/evaluation/SimulationLearningCurvePanel.java
  inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/DocumentRepositoryEditorPanel.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AbstractInfoPanel.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/QualifierFeatureEditor.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseIriPanel.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/RootConceptsPanel.java
Labels: ⚙️Refactoring

#1542 #1539 - String-based recommender on layers with character-level granularity
  inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
  inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderFactory.java
  inception-imls-stringmatch/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_string.adoc
  inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTest.java
Labels: Module: Recommender, 🆕Enhancement
