Repository inception-project/inception, pull requests merged in 2020-10, with the labels that each got.

#1814 #1810 Dismissing recommendations no longer works
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
Labels: Module: Recommender, 🐛Bug

#1815 #1812 Tutorial fails on setting tabs
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
  inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/settings/ProjectWorkloadSettingsPanelFactory.java
Labels: 🐛Bug

#1761 #1760 - Getting started
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_Sidebar_closed.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_Sidebar_open.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_agreement.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_annotation_panel.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_create_users.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_curation.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_documents.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_download_example_project.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_example_for_annotations.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_first_annotation.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_guidelines.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_import_project.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_kb_page.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_kbs.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_layers.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_login.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_monitoring.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_open_a_project.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_recommenders.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_settings.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_starting_the_jar_I.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_starting_the_jar_II.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_tagset_create.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_tagset_link.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_tagset_use.png
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/images/getting_started_users.png
Labels: 📖Documentation

#1835 #1828 - Error in importing projects
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUtils.java
  pom.xml
Labels: Module: Project Search, 🐛Bug

#1834 Bugfix/1825 duplicates in search
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/FeatureIndexingSupport.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchResult.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchService.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/event/SearchQueryEvent.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndex.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/Task.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
Labels: Module: Project Search, 🐛Bug

#1839 #1832 - Display project id in developer mode
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
Labels: 🆕Enhancement

#1831 #1830 - Upgrade to Wicket 9
  inception-external-search-pubannotation/pom.xml
  inception-external-search-pubannotation/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/PubAnnotationProviderTest.java
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
  inception-ui-kb/pom.xml
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/sass/KnowledgeBasePageLRR.java
  pom.xml
Labels: Requires upstream changes, ⚙️Refactoring
