Repository inception-project/inception, pull requests merged in 2020-12, with the labels that each got.

#1720 External search solr
  .gitignore
  inception-app-webapp/pom.xml
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
  inception-external-search-solr/marker-wicket-module
  inception-external-search-solr/pom.xml
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProvider.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProviderFactory.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/config/SolrSearchDocumentRepositoryAutoConfiguration.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraits.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraitsEditor.html
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraitsEditor.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraitsEditor.properties
  inception-external-search-solr/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-solr.adoc
  inception-external-search-solr/src/main/resources/META-INF/spring.factories
  inception-external-search-solr/src/test/java/SolrSearchProviderTest.java
  pom.xml
Labels: 🆕Enhancement

#1878 #276 Support solr based external indexes
  inception-external-search-solr/pom.xml
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProvider.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProviderFactory.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/config/SolrSearchDocumentRepositoryAutoConfiguration.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraits.java
  inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraitsEditor.java
  inception-external-search-solr/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProviderTest.java
  installEclipseSettings.sh
  pom.xml
Labels: 🆕Enhancement

#1872 #1765 Curation Sidebar: Should be able to change user even when finished
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationService.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.html
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.properties
  inception-curation/src/main/resources/META-INF/asciidoc/user-guide/curation-sidebar.adoc
  inception-curation/src/main/resources/META-INF/asciidoc/user-guide/images/curation-sidebar.png
  pom.xml
Labels: Module: Curation, Requires upstream changes, 🐛Bug

#1888 #1885 - Update Java version in Docker
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/docker/README.md
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContextInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionWebInitializer.java
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose.yml
  inception-docker/README.md
  inception-docker/pom.xml
  inception-docker/src/main/docker/Dockerfile
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/TaskConsumer.java
  pom.xml
Labels: 🆕Enhancement

#1892 #1881 Search sidebar shows results for wrong user when viewing other …
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
Labels: Module: Project Search, 🐛Bug

#1901 #1899 - Do not spam log with stack traces for invalid user actions
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
Labels: ⚙️Refactoring

#1900 #1898 - TCF export not working
  inception-imls-weblicht/pom.xml
  pom.xml
Labels: 🐛Bug

#1904 #1903 - Exception when searching for single character with embedded KB
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
Labels: Module: Knowledge Base, 🐛Bug

#1906 #1905 - Equivalent tasks run in parallel
  inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/InspectableThreadPoolExecutor.java
  inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java
  inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
Labels: Module: Scheduler, 🐛Bug

#1910 #1848 - Documentation improvements
  inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup.adoc
Labels: 📖Documentation

#1902 Bugfix/1845 mtas indexing throws lots of exceptions
  inception-build/src/main/resources/inception/checkstyle.xml
  inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java
  inception-search-core/pom.xml
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/config/SearchServiceAutoConfiguration.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/config/SearchServiceProperties.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/config/SearchServicePropertiesImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/IndexScheduler.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/IndexSchedulerImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/TaskConsumer.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexFactory.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  pom.xml
Labels: Module: Project Search, 🐛Bug

#1916 #1915 - Add json logger for log4j2
  inception-app-webapp/pom.xml
  pom.xml
Labels: Module: Logging, 🆕Enhancement

#1914 #1240 - Allow adding external jars to the standalone application
  inception-app-webapp/pom.xml
  inception-boot-loader/LICENSE.txt
  inception-boot-loader/pom.xml
  inception-boot-loader/src/main/java/de/tudarmstadt/ukp/inception/bootloader/ExtensibleClasspathEnabledWarLauncher.java
  inception-boot-loader/src/main/java/de/tudarmstadt/ukp/inception/bootloader/ExtensibleClasspathEnabledWarLayoutFactory.java
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc
  inception-example-imls-data-majority/pom.xml
  pom.xml
Labels: 🆕Enhancement
