Repository inception-project/inception, pull requests merged in 2020-07, with the labels that each got.

#1751 #1744 Update dev-guide release section
  inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/release.adoc
Labels: 📖Documentation

#1755 #1270 new user hints - sidebars
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.html
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
Labels: 🕶️UX

#1705 [#1704] Result lists in sidebars too small on smaller screens
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.properties
Labels: Module: Annotation, 🆕Enhancement, 🕶️UX

#1768 #1763 Change Home Button references in documentation
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
  inception-ui-core/src/main/resources/META-INF/asciidoc/user-guide/dashboard_menubar.adoc
  inception-ui-core/src/main/resources/META-INF/asciidoc/user-guide/dashboard_project-view.adoc
Labels: 📖Documentation

#1770 #1766 Unit tests on master are failing on Jenkins
  inception-imls-dl4j/pom.xml
  inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
Labels: Critical, Needs Review, Testing, 🐛Bug

#1762 #1747 Curation sidebar causes very large projects to hang
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationService.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.html
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.properties
  inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationServiceTest.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.java
Labels: Needs Review, Requires upstream changes, 🐛Bug, 🚀Performance

#1772 #1771 Hide Agreement menu item if not enough users
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/menu/AgreementPageMenuItem.java
Labels: Module: Agreement, Needs Review, 🆕Enhancement, 🕶️UX

#1783 #1773 Project import on projects page: add option to add missing users
  inception-ui-core/pom.xml
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
  inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/page/settings/ProjectWorkloadSettingsPanelFactory.java
Labels: 🆕Enhancement
