Repository inception-project/inception, pull requests merged in 2020-06, with the labels that each got.

#1713 #1711 - Adjust to api changes: Improve annotation detail sidebar architecture and performance
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/resources/application.properties
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java
  inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureEditor.html
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/recommendation/RecommenderTestHelper.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
  pom.xml
Labels: Module: Annotation, ⚙️Refactoring

#1724 #1721 - Using PDF editor with wrong format
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
Labels: Module: PDF editor, 🐛Bug

#1700 #1697 - Adjust to upstream changes: Better CAS management
  inception-concept-linking/pom.xml
  inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/NamedEntityLinkerTest.java
  inception-example-imls-data-majority/pom.xml
  inception-example-imls-data-majority/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommenderTest.java
  inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderIntegrationTest.java
  inception-imls-lapps/pom.xml
  inception-imls-lapps/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/LappsGridRecommenderConformityTest.java
  inception-imls-lapps/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/LappsRecommenderIntegrationTest.java
  inception-imls-opennlp/pom.xml
  inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTest.java
  inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTest.java
  inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTest.java
  inception-imls-stringmatch/pom.xml
  inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTest.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
  inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
  inception-search-core/pom.xml
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchCasUtils.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexAnnotationDocumentTask.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexSourceDocumentTask.java
  inception-search-mtas/pom.xml
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception-search-mtas/src/test/resources/log4j2.xml
Labels: Requires upstream changes, ⚙️Refactoring

#1716 #1715 AL sidebar is missing
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/config/ActiveLearningAutoConfiguration.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/metrics/RecommendationMetricsImpl.java
Labels: Module: Active Learning, 🐛Bug

#1718 #1717 - Adjust to upstream changes: Improve brat rendering
  inception-app-webapp/src/main/resources/log4j2.xml
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
Labels: ⚙️Refactoring

#1731 #1729 - Make KB links beautiful
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePage.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
Labels: Module: Knowledge Base, 🆕Enhancement, 🕶️UX

#1733 #1732 - Upgrade dependencies (0.17.0)
  pom.xml
Labels: ⚙️Refactoring

#1737 #1708 - Disable Yago
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseProfile.java
  inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseProfileDeserializationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
  inception-kb/src/test/resources/log4j2.xml
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
  pom.xml
Labels: Module: Knowledge Base, 🆕Enhancement

#1740 #1730 Instances/Mention box has two scrollbars
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstanceListPanel.html
Labels: Module: Knowledge Base, 🐛Bug, 🕶️UX

#1739 #1714 Curation entities in annotation view are visible also on 'ANNOT…
  inception-curation/pom.xml
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationService.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
  inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationServiceTest.java
Labels: Needs Review, 🐛Bug

#1743 #1742 CurationSidebar: error when no users are selected
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
Labels: 🐛Bug
