Repository inception-project/inception, pull requests merged in 2020-05, with the labels that each got.

#1687 #1533 - Periodical commit of MTAS index
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
Labels: Module: Project Search, 🐛Bug

#1684 #1679 - Cannot delete project
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndexRegistryImpl.java
  inception-search-mtas/src/main/resources/META-INF/spring.factories
Labels: Module: Project Search, Needs Review, 🐛Bug

#1689 #1688 - Upgrade dependencies (0.16.0)
  pom.xml
Labels: Needs Review, ⚙️Refactoring

#1685 #1654 - NPE on session destruction
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
Labels: 🐛Bug

#1696 #1695 - Update documentation for deployment via systemd
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc
Labels: 📖Documentation

#1699 #1698 - Unable to enable LAPPS recommender
  inception-imls-lapps/src/main/resources/META-INF/spring.factories
  pom.xml
Labels: Module: Recommender, 🐛Bug

#1691 #1662 - Impossible to create annotations via Search
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
Labels: Module: Project Search, Needs Review, 🐛Bug

#1676 #1668 - Eager tabbed browsing on projects page can lead to IOOBE
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/WicketApplication.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderProjectSettingsPanelFactory.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/DocumentRepositoryProjectSettingsPanelFactory.java
Labels: Module: Dashboard, 🐛Bug

#1702 #1701 - Support advanced AJP secret
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc
Labels: Needs Review, 🆕Enhancement

#1706 #1681 Add prometheus monitoring
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/metrics_monitoring.adoc
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/metrics/RecommendationMetrics.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/metrics/RecommendationMetricsImpl.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
Labels: Needs Review, Requires upstream changes

#1710 #1709 - Improve speed when importing/deleting large projects
  inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/exporter/DocumentRepositoryExporter.java
  inception-log/pom.xml
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
Labels: ⚙️Refactoring
