Repository inception-project/inception, pull requests merged in 2020-04, with the labels that each got.

#1656 #1655 - Exception when opening login page
  inception-doc/src/main/resources/META-INF/asciidoc/common/systemrequirements.adoc
  pom.xml
Labels: Needs Review, 🐛Bug

#1660 #1658 - Port and protocol information for external document repositories ignored
  inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java
  inception-external-search-elastic/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-elasticsearch.adoc
Labels: Needs Review, 🐛Bug

#1663 #1533 - Periodical commit of MTAS index
  inception-search-core/pom.xml
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchService.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/config/SearchServiceAutoConfiguration.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndex.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndexFactory.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndexFactoryImplBase.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/IndexScheduler.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/IndexSchedulerImpl.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/ReindexTask.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexFactory.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
  inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProvider.java
Labels: Module: Project Search, ⚙️Refactoring

#1671 #1629 - Adjust to upstream changes for annotation service impl refactoring
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/config/DocumentMetadataLayerSupportAutoConfiguration.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerSupport.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
  inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  inception-search-mtas/pom.xml
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexFactory.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/config/MtasDocumentIndexAutoConfiguration.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/recommendation/RecommenderTestHelper.java
  inception-ui-kb/pom.xml
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/FactLayerInitializer.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/NamedEntityIdentifierFeatureInitializer.java
Labels: ⚙️Refactoring

#1674 #1672 - Resilience against missing feature/layer supports
  inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/sidebar/ImageSidebar.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/VisibilityCalculationTests.java
Labels: ⚙️Refactoring

#1682 #1675 Documentation for TEI P5 format is wrong
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-tei.adoc
Labels: Needs Review, 📖Documentation
