Repository inception-project/inception, pull requests merged in 2020-02, with the labels that each got.

#1611 Bugfix/ignore tests
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
Labels: Testing

#1405 #1270 hints for new users
  inception-app-webapp/pom.xml
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
  inception-ui-core/NOTICE.txt
  inception-ui-core/pom.xml
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/TutorialFooterItem.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/TutorialFooterPanel.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/TutorialFooterPanel.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/EnjoyHintJsReference.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/TutorialJavascriptReference.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/enjoyhint.js
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
  pom.xml
Labels: 🆕Enhancement, 🕶️UX

#1622 Feature/1618 adjust to upstream api changes related to coloring
  inception-external-search-pubannotation/pom.xml
  inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlAnnotationEditor.java
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureTraits.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerAdapter.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerSupport.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/render/PdfAnnoRenderer.java
  inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRenderer.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationTypeRenderer.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
Labels: ⚙️Refactoring

#1598 #1597 - Several format examples cannot be used copy-paste
  inception-app-webapp/pom.xml
  inception-doc/pom.xml
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-imscwb.adoc
  inception-doc/src/test/java/de/tudarmstadt/ukp/inception/doc/GenerateDocumentation.java
  pom.xml
Labels: 🐛Bug, 📖Documentation

#1624 #1623 - Reduce time when importing a large number of documents via the UI
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/ImsCwbFormatSupport.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/LifFormatSupport.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/NifFormatSupport.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/PerseusFormatSupport.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/TeiFormatSupport.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/UimaInlineXmlTeiFormatSupport.java
  inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/format/PubAnnotationSectionsFormatSupport.java
  inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlFormatSupport.java
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfFormatSupport.java
  inception-ui-core/pom.xml
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java
Labels: ⚙️Refactoring, 🚀Performance
