Repository inception-project/inception, pull requests merged in 2020-11, with the labels that each got.

#1850 #1848 - Documentation-improvements
  inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
Labels: 📖Documentation

#1853 #1852 - Default ElasticSearch document repository settings do not work
  inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraits.java
  inception-external-search-elastic/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-elasticsearch.adoc
Labels: 🐛Bug

#1862 #1859 - Upgrade dependencies
  pom.xml
Labels: ⚙️Refactoring

#1863 #1860 - Layers without features are not indexed for search
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
  inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
Labels: Module: Project Search, 🐛Bug

#1871 Feature/1870 improve roundtrip times on annotation page
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java
  inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlAnnotationEditor.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/render/PdfAnnoRenderer.java
  inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRenderer.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
  pom.xml
Labels: ⚙️Refactoring

#1869 #1868 - Deadlock importing project with large tagset on HSQLDB
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
  pom.xml
Labels: 🐛Bug
