Repository inception-project/inception, pull requests merged in 2021-08, with the labels that each got.

#2527 #2526 - Allow selective disabling of COEP for developers
  inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/PatternMatchingCrossOriginEmbedderPolicyRequestCycleListener.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
Labels: ⚙️Refactoring

#2529 #2524 - Curation no longer works
  inception/inception-curation-legacy/pom.xml
  inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java
  inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/CurationDocumentServiceImplTest.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
Labels: Module: Curation, 🐛Bug

#2528 Refactoring/2423 clean up brat code
  inception/.editorconfig
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/AnnotationMarker.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
Labels: Module: brat, ⚙️Refactoring

#2531 #2449 - Jumping from annotation editor to PDF annotation via recent activity does not work
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfAnnoPanel.java
Labels: Module: Annotation, Module: Dashboard, Module: PDF editor, 🐛Bug

#2530 #2426 - Difference in labelling of annotation marker vs identifier lookup
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureValueType.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBaseProperties.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBasePropertiesImpl.java
  inception/inception-kb/src/main/resources/META-INF/asciidoc/admin-guide/settings_knowledgebase.adoc
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/config/KnowledgeBaseServiceUIAutoConfiguration.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupport.java
  inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/knowledge_base.adoc
  inception/inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupportTest.java
  inception/inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java
Labels: Module: Knowledge Base, 🐛Bug

#2532 #2522 - Opening sidebar changes document
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
Labels: Module: Annotation, Module: Dashboard, 🐛Bug

#2515 Feature/2176 long relations hide arcs
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerTraits.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerTraitsEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerTraitsEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java
  inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRendererTest.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationRenderer.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
Labels: 🆕Enhancement, Module: Recommender

#2540 #2522 - Opening sidebar changes document
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
  inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.html
Labels: 🐛Bug, Module: Annotation, Module: Curation

#2535 #2534 Add word conversion colab notebook
  notebooks/annotated_word_files_to_cas_xmi.ipynb
Labels: 📖Documentation

#2545 #2543 Show export progress only on export
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.html
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.java
Labels: 🕶️UX, Module: Project Settings

#2542 #2541 Cannot export project when curation started
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportCuratedDocumentsTask.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java
Labels: 🐛Bug

#2546 #2491 - Bulk-deletion does not unselect annotation
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
Labels: 🐛Bug, Module: Project Search

#2547 #2286 - Upgrade dependencies
  inception/pom.xml
Labels: ⚙️Refactoring

#2548 #2505 - Slot features should be ignored when comparing annotations for the purpose of bulk-annotation
  inception/inception-search-core/src/main/resources/META-INF/asciidoc/user-guide/search-core.adoc
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
Labels: 🐛Bug, Module: Project Search

#2549 #2544 Export cannot be cancelled
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportCuratedDocumentsTask.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportFullProjectTask.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/SourceDocumentExporter.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExportService.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
  inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporterTest.java
Labels: 🐛Bug

#2552 #1614 Inconsistent behaviour when two recommenders are set
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception/inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation.adoc
Labels: 📖Documentation

#2550 #2462 - Ability to bulk assign texts to annotators based on filter
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.properties
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadFilterPanel.html
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadFilterPanel.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/event/FilterStateChangedEvent.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/AnnotatorColumn.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/DocumentMatrixDataProvider.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/DocumentMatrixRow.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/Filter.java
  inception/inception-workload-matrix/src/main/resources/META-INF/asciidoc/user-guide/workload_matrix.adoc
Labels: 🆕Enhancement, Module: Workload, Module: Monitoring

#2555 #2495 - Ignorable features for curation mode
  inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
  inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
  inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTestBase.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/LayerExporter.java
  inception/inception-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedAnnotationFeature.java
  inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
  inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
  inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
Labels: 🆕Enhancement, Module: Curation

#2558 #2383 - getting started sidebar
  inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
Labels: 🐛Bug, 📖Documentation

#2563 #2562 - Project name no longer unique
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/LayerBehaviorRegistryImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/config/ProjectExportServiceAutoConfiguration.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
  inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/config/CurationDocumentServiceAutoConfiguration.java
  inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationServiceTest.java
  inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/adapter/FeatureValueUpdatedEventAdapterTest.java
  inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
  inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
  inception/inception-project/pom.xml
  inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/config/ProjectInitializersAutoConfiguration.java
  inception/inception-project/src/test/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImplTest.java
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/LegacyRemoteApiController.java
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/model/RProject.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/AeroRemoteApiControllerTest.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
  inception/inception-scheduling/src/test/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceTest.java
  inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception/inception-sharing/src/test/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImplTest.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.html
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java
  inception/inception-versioning/src/test/java/de/tudarmstadt/ukp/inception/versioning/VersioningServiceImplTest.java
  inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventMessageControllerImplTest.java
  inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
Labels: 🆕Enhancement

#2566 #2475 - Upgrade to Bootstrap 5
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsConfigurationPanel.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.html
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTraitsEditor.html
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/settings/StringMatchingRecommenderTraitsEditor.html
  inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.html
  inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.html
  inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.html
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/bootstrap.scss
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.vue
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.html
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
  inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AbstractInfoPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptListPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptTreePanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstanceListPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePage.properties
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/PropertyListPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/QuerySettingsPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementsPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/IRIValueEditor.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/StringLiteralValueEditor.html
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
  inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagEditorPanel.html
  inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.html
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
Labels: 🆕Enhancement

#2572 #2571 - Email validation kicks in even if it is turned off
  inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
Labels: 🐛Bug, Module: Recommender

#2570 #2475 - Upgrade to Bootstrap 5
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/feedback/FeedbackPanelExtension.js
Labels: 🆕Enhancement, Module: Recommender

#2573 #2286 - Upgrade dependencies (21.0)
  inception/inception-app-webapp/pom.xml
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception/inception-boot-loader/src/main/java/de/tudarmstadt/ukp/inception/bootloader/ExtensibleClasspathEnabledWarLayoutFactory.java
  inception/inception-export/pom.xml
  inception/inception-security/pom.xml
  inception/pom.xml
Labels: ⚙️Refactoring

#2575 #2312 - Add support for new external recommender v2
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommender.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderFactory.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraits.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.html
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.properties
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/config/ExternalRecommenderAutoConfiguration.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/config/ExternalRecommenderProperties.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/config/ExternalRecommenderPropertiesImpl.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/messages/PredictionRequest.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/messages/PredictionResponse.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/messages/TrainingRequest.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/model/Document.java
  inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/model/Metadata.java
  inception/inception-imls-external/src/main/resources/META-INF/spring.factories
  inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/util/InceptionAssertions.java
  inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderIntegrationTest.java
  inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/RemoteStringMatchingNerRecommender.java
Labels: Module: Recommender, ⚙️Refactoring

#2576 #2574 - Pull project export code out of api-dao module
  inception/inception-api-dao/pom.xml
  inception/inception-api-dao/src/main/resources/META-INF/spring.factories
  inception/inception-project-export/LICENSE.txt
  inception/inception-project-export/pom.xml
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportCuratedDocumentsTask.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportFullProjectTask.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportTask_ImplBase.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/config/ProjectExportServiceAutoConfiguration.java
  inception/inception-project-export/src/main/resources/META-INF/spring.factories
  inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/AnnotationDocumentsExporterTest.java
  inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/CuratedDocumentsExporterTest.java
  inception/inception-project-export/src/test/resources/exports/Export+Test+-+Curated+annotation+project_3_6_1.zip
  inception/inception-project-export/src/test/resources/exports/Export+Test+-+Curated+correction+project_3_4_8.zip
  inception/inception-project-export/src/test/resources/exports/Export+Test+-+Curated+correction+project_3_6_1.zip
  inception/inception-project-export/src/test/resources/log4j2.xml
  inception/inception-remote/pom.xml
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/AeroRemoteApiControllerTest.java
  inception/pom.xml
Labels: ⚙️Refactoring
