Repository inception-project/inception, pull requests merged in 2021-01, with the labels that each got.

#1918 #1917 - Recent activity does not discern well between annotation and curation
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
  inception-ui-core/pom.xml
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java
Labels: Module: Dashboard, 🐛Bug

#1922 #1921 - Import of project with read-only KB fails
  inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
Labels: Module: Knowledge Base, 🐛Bug

#1920 #1919 - Allow excluding events from being logged
  inception-log/pom.xml
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/TagEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingAutoConfiguration.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingProperties.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingPropertiesImpl.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/TagDetails.java
  inception-log/src/main/resources/META-INF/spring.factories
Labels: Module: Logging, 🆕Enhancement

#1924 #1923 - Error during log writing creates unparseable JSON
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/log/ActiveLearningRecommendationEventAdapter.java
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/log/ActiveLearningSuggestionOfferedAdapter.java
  inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/log/ExternalSearchQueryEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AfterDocumentCreatedEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AfterProjectCreatedEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AnnotationStateChangedEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/DocumentStateChangedEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/EventLoggingAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/FeatureValueUpdatedEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/GenericEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/ProjectStateChangedEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/RelationEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/SpanCreatedEventAdapter.java
  inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/SpanDeletedEventAdapter.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommendationAcceptedEventAdapter.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommendationRejectedEventAdapter.java
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommenderEvaluationResultEventAdapter.java
  inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/log/SearchQueryEventAdapter.java
Labels: Module: Logging, 🐛Bug

#1929 #1928 - Support deletion of layers
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/FactLayerInitializer.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/NamedEntityIdentifierFeatureInitializer.java
Labels: Module: Project Settings, 🆕Enhancement

#1927 #1926 - Enable Hibernate 2nd-level cache
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception-app-webapp/src/main/resources/application.properties
  inception-app-webapp/src/main/resources/application.yml
  inception-app-webapp/src/main/resources/ehcache.xml
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LearningRecordChangeLocationType.java
  inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LearningRecordUserActionType.java
Labels: ⚙️Refactoring

#1940 Adjust to upstream changes
  inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImplTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplImportExportIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplQualifierIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
  inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseSubPropertyLabelTest.java
  inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImplIntegrationTest.java
  inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
  inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
Labels: ⚙️Refactoring

#1939 #1938 - Edit project name directly on dashboard
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/Dashlet_ImplBase.java
Labels: Module: Dashboard, 🆕Enhancement

#1937 #1936 - Change menu item visibility
  inception-recommendation/pom.xml
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/evaluation/EvaluationSimulationPageMenuItem.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menu/CurationPageMenuItem.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menu/ProjectSettingsPageMenuItem.java
Labels: Module: Dashboard, ⚙️Refactoring

#1944 #1943 - Quickly create simple project
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicProjectInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationLayerInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationTagSetInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanLayerInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanRecommenderInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanTagSetInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/StandardProjectInitializer.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/QuickProjectInitializer.java
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/FactLayerInitializer.java
Labels: Module: Dashboard, 🆕Enhancement

#1955 #1954 - Info badge and link to not appear immediately when linking concept
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
Labels: Module: Entity Linking, 🐛Bug

#1837 #1836-Documentation-for-workload
  inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.properties
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/WicketApplication.properties
  inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.properties
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide/other_editors.adoc
  inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/sidebar/ImageSidebar.properties
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/evaluation/EvaluationSimulationPage.properties
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/ProjectRecommendersPanel.properties
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.properties
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/AdminDashboardPage.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectImportPanel.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.properties
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/DocumentDetailsPage.properties
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.properties
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/DocumentRepositoryEditorPanel.properties
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/DocumentRepositoryListPanel.properties
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/ProjectDocumentRepositoriesPanel.properties
  inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.properties
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.properties
  inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.properties
  inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/project/WorkloadSettingsPanel.properties
  inception-workload/src/main/resources/META-INF/asciidoc/user-guide/images/workload.png
  inception-workload/src/main/resources/META-INF/asciidoc/user-guide/images/workload_settings.png
  inception-workload/src/main/resources/META-INF/asciidoc/user-guide/workload.adoc
Labels: 📖Documentation

#1884 #1883 Clearer label in recommendation sidebar
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
  inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/annotation_recommendation.adoc
  inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/images/recommendation_sidebar.png
  pom.xml
Labels: Module: Recommender, 🆕Enhancement, 📖Documentation

#1330 #1218 - Structured Review
  inception-app-webapp/pom.xml
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
  inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
  inception-review-editor/LICENSE.txt
  inception-review-editor/marker-wicket-module
  inception-review-editor/pom.xml
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/AnnotationListItem.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/AnnotationPanel.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/DocumentAnnotationPanel.html
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/DocumentAnnotationPanel.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/ReviewEditor.html
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/ReviewEditor.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/ReviewEditorFactory.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/SpanAnnotationPanel.html
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/SpanAnnotationPanel.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/StructuredReviewDraftPanel.html
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/StructuredReviewDraftPanel.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/UnlinkedAnnotationPanel.html
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/UnlinkedAnnotationPanel.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/config/NoPagingStrategy.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/config/ReviewEditorProperties.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/config/ReviewEditorPropertiesImpl.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/event/RefreshEvent.java
  inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/event/SelectAnnotationEvent.java
  installEclipseSettings.sh
  pom.xml
Labels: 🆕Enhancement, 🕶️UX

#1956 #1943 - Quickly create simple project
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/EntityLinkingProjectInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/NamedEntityIdentifierStringRecommenderInitializer.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/WikiDataKnowledgeBaseInitializer.java
Labels: 🆕Enhancement

#1949 #1841 - Dev Guide: Use min Java version for release
  .github/ISSUE_TEMPLATE/release-bugfix.md
  .github/ISSUE_TEMPLATE/release-feature.md
  inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/release.adoc
Labels: 📖Documentation

#1952 #1951 - Custom error page
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/WicketApplication.java
  inception-app-webapp/src/main/resources/application.yml
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorListener.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.properties
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorTestPage.java
Labels: 🆕Enhancement

#1964 #1551 - PDF editor sometimes has trouble loading the PDF
  inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfAnnoPanel.java
Labels: Module: PDF editor, 🐛Bug

#1967 #1966 No images in guides
  inception-app-webapp/pom.xml
Labels: 🐛Bug

#1962 Feature/1876 sharing project links
  inception-app-webapp/pom.xml
  inception-app-webapp/src/main/resources/db/changelog/db.changelog-master.xml
  inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
  inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
  inception-sharing/marker-wicket-module
  inception-sharing/pom.xml
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.html
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.properties
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteService.java
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImpl.java
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/config/InviteServiceAutoConfiguration.java
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/model/ProjectInvite.java
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.html
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.java
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.properties
  inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanelFactory.java
  inception-sharing/src/main/resources/META-INF/asciidoc/admin-guide/settings_sharing.adoc
  inception-sharing/src/main/resources/META-INF/asciidoc/user-guide/images/sharing_settings.png
  inception-sharing/src/main/resources/META-INF/asciidoc/user-guide/projects_sharing.adoc
  inception-sharing/src/main/resources/META-INF/spring.factories
  inception-sharing/src/main/resources/de/tudarmstadt/ukp/inception/sharing/model/db-changelog.xml
  inception-sharing/src/test/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImplTest.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.html
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.java
  inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java
  installEclipseSettings.sh
  pom.xml
Labels: Module: Citizenception, 🆕Enhancement

#1969 #1968 - Finishing document does not move on
  inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.java
  inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java
  inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/workflow/WorkflowExtension.java
Labels: Module: Workload, 🐛Bug
