Repository inception-project/inception, pull requests merged in 2021-05, with the labels that each got.

#2249 #2247 - Insufficient eval data should not fail eval if threshold is 0
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommender.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html
Labels: Module: Recommender, 🐛Bug

#2251 #2229 - UI: "Cancel" in curation modal does not return to project dashboard
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialog.java
Labels: Module: Annotation, Module: Curation, 🐛Bug

#2244 #2243 - Directly select tags for small tagsets
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/StringFeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/config/PrimitiveUimaFeatureSupportProperties.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureTraits.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraits.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.java
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_annotation-editor.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
  inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
  inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_tagsets.adoc
Labels: Module: Annotation, 🆕Enhancement

#2259 #2098 - Annotation gets slower and slower followed by aw snap
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/ChartPanel.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
Labels: Module: Annotation, 🐛Bug

#2248 #2246 - Simple span/relation project should include relation recommender
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/ProjectInitializersAutoConfiguration.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicProjectInitializer.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationLayerInitializer.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationRecommenderInitializer.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/config/StringMatchingRecommenderAutoConfiguration.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommenderFactory.java
  inception/inception-imls-stringmatch/src/main/resources/META-INF/asciidoc/admin-guide/settings_string_relation_recommender.adoc
Labels: 🆕Enhancement

#2254 #2253 - Make starting INCEpTION nicer
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/icon.png
  inception/inception-support-standalone/pom.xml
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/LoadingSplashScreen.java
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialog.java
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
  inception/inception-support-standalone/src/main/resources/icon.png
  inception/inception-support-standalone/src/main/resources/splash.png
Labels: 🆕Enhancement, 🕶️UX

#2268 Feature/2161 upgrade dependencies
  inception/pom.xml
Labels: ⚙️Refactoring

#2269 #2267 - imported Webanno_tsv_3.2 is not as same as the original annotation
  inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java
  inception/inception-io-webanno-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3WriterTestBase.java
  inception/inception-io-webanno-tsv/src/test/resources/tsv3-suite/testStackedSubMultiTokenSpanWithFeatureValue/reference.tsv
  inception/inception-io-webanno-tsv/src/test/resources/tsv3-suite/testSubMultiTokenSpanWithFeatureValue/reference.tsv
  inception/inception-io-webanno-tsv/src/test/resources/tsv3-suite/testSubTokenPrefix/reference.tsv
  inception/inception-io-webanno-tsv/src/test/resources/tsv3-suite/testSubTokenPrefix/reference.xmi
  inception/inception-io-webanno-tsv/src/test/resources/tsv3-suite/testSubTokenRelation/reference.tsv
  inception/inception-io-webanno-tsv/src/test/resources/tsv3-suite/testSubTokenRelation/reference.xmi
Labels: Module: TSV, 🐛Bug

#2207 #2158 - Change findExtension into a method that returns an optional value
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupportRegistry.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupportRegistryImpl.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraitsEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureTraitsEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextFeatureEditorBase.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsConfigurationPanel.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsPanel.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/LayerSupport_ImplBase.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer_ImplBase.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
  inception/inception-concept-linking/pom.xml
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerFactory.java
  inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/NamedEntityLinkerTest.java
  inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTest.java
  inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRelationRenderer.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/PrimitiveUimaIndexingSupport.java
  inception/inception-support/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/CachingContextLookupExtensionPoint_ImplBase.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ContextLookupExtensionPoint.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint_ImplBase.java
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/FeatureEditorListPanel.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/DisabledKBWarning.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/FactLinkingServiceImpl.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/QualifierFeatureEditor.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/SubjectObjectFeatureEditor.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupport.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.java
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/project/WorkloadSettingsPanel.java
  pom.xml
Labels: ⚙️Refactoring

#2274 Feature/2260 create log file in inception folder by default
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception/inception-app-webapp/src/main/resources/log4j2.xml
  inception/inception-support-standalone/pom.xml
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/LoadingSplashScreen.java
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java
  inception/inception-support-standalone/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.properties
  inception/inception-support/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/logging/RingBufferAppender.java
Labels: 🆕Enhancement

#2280 #2279 No longer able to create new users
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserSelectionPanel.java
Labels: 🐛Bug

#2287 #2264 - Risk of permanently unfinished documents using dynamic workflow
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  inception/inception-versioning/src/test/resources/log4j2.xml
  inception/inception-workload-dynamic/pom.xml
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl.java
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/config/DynamicWorkloadManagerAutoConfiguration.java
  inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DefaultWorkflowExtensionTest.java
  inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/Fixtures.java
  inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/workflow/types/DynamicWorkloadExtensionImplTest.java
  inception/inception-workload-dynamic/src/test/resources/log4j2.xml
  inception/inception-workload/pom.xml
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManagementService.java
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManagementServiceImpl.java
Labels: Module: Workload, 🆕Enhancement

#2290 #2276 - More Spring auto-configuration
  inception/inception-active-learning/pom.xml
  inception/inception-api-annotation/pom.xml
  inception/inception-api-dao/pom.xml
  inception/inception-api/pom.xml
  inception/inception-brat-editor/pom.xml
  inception/inception-concept-linking/pom.xml
  inception/inception-constraints/pom.xml
  inception/inception-curation-legacy/pom.xml
  inception/inception-curation/pom.xml
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationRenderer.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/config/CurationServiceAutoConfiguration.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/AutomaticMergeStrategy.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ManualMergeStrategy.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebarFactory.java
  inception/inception-curation/src/main/resources/META-INF/spring.factories
  inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationServiceTest.java
  inception/inception-curation/src/test/resources/log4j2.xml
  inception/inception-example-imls-data-majority/pom.xml
  inception/inception-external-search-core/pom.xml
  inception/inception-external-search-elastic/pom.xml
  inception/inception-external-search-pubannotation/pom.xml
  inception/inception-external-search-solr/pom.xml
  inception/inception-imls-dl4j/pom.xml
  inception/inception-imls-external/pom.xml
  inception/inception-imls-lapps/pom.xml
  inception/inception-imls-opennlp/pom.xml
  inception/inception-imls-stringmatch/pom.xml
  inception/inception-io-html/pom.xml
  inception/inception-io-text/pom.xml
  inception/inception-io-webanno-tsv/pom.xml
  inception/inception-kb/pom.xml
  inception/inception-log/pom.xml
  inception/inception-pdf-editor/pom.xml
  inception/inception-preferences/pom.xml
  inception/inception-project/pom.xml
  inception/inception-recommendation-api/pom.xml
  inception/inception-recommendation/pom.xml
  inception/inception-scheduling/pom.xml
  inception/inception-search-mtas/pom.xml
  inception/inception-sharing/pom.xml
  inception/inception-support/pom.xml
  inception/inception-testing/pom.xml
  inception/inception-ui-kb/pom.xml
  inception/inception-versioning/pom.xml
  inception/pom.xml
Labels: ⚙️Refactoring

#2292 2176 nicer relations rec
  inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/SpanLayerSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VObject.java
  inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapterTest.java
  inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRendererTest.java
  inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRendererTest.java
  inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/BratRendererTest.java
  inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTestBase.java
  inception/inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
Labels: 🆕Enhancement

#2051 #2046 List logged events with spring websockets
  inception/inception-app-webapp/pom.xml
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception/inception-app-webapp/src/main/resources/application.yml
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  inception/inception-log/pom.xml
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/GenericEventAdapter.java
  inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImplIntegrationTest.java
  inception/inception-testing/pom.xml
  inception/inception-testing/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketTest.java
  inception/inception-testing/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketTestPage.java
  inception/inception-websocket/marker-wicket-module
  inception/inception-websocket/pom.xml
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventMessageController.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventMessageControllerImpl.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/config/WebsocketConfig.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/config/WebsocketSecurityConfig.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/footer/LoggedEventFooterItem.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/footer/LoggedEventFooterPanel.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/footer/LoggedEventFooterPanel.vue
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/model/LoggedEventMessage.java
  inception/inception-websocket/src/main/resources/META-INF/asciidoc/admin-guide/settings_websocket.adoc
  inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventMessageServiceImplTest.java
  inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
  inception/installEclipseSettings.sh
  inception/pom.xml
Labels: 🆕Enhancement

#1822 #1634 - Explicit UI for accepting/rejecting recommendations
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VObject.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.html
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/AcceptActionResponse.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/NumericBooleanSerializer.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/RejectActionResponse.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/Entity.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/EntityAttributes.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/style-ui.scss
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js
  inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/display/model/EntityTest.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderProperties.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderPropertiesImpl.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRelationRenderer.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRenderer.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationTypeRenderer.java
  inception/inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/annotation_recommendation.adoc
Labels: Module: Recommender, 🆕Enhancement

#2296 #2295 Links to user guide do not work
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/help/DocLink.java
  inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.html
  inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.java
  inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.properties
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.properties
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.properties
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.properties
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/AdminDashboardPage.properties
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.properties
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/ProjectSettingsDashboardPageBase.properties
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.html
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePage.properties
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectSettingsPage.properties
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.properties
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.properties
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.properties
  inception/inception-workload-ui/src/main/java/de/tudarmstadt/ukp/inception/workload/project/WorkloadSettingsPanel.html
  inception/inception-workload-ui/src/main/java/de/tudarmstadt/ukp/inception/workload/project/WorkloadSettingsPanel.java
  inception/inception-workload-ui/src/main/java/de/tudarmstadt/ukp/inception/workload/project/WorkloadSettingsPanel.properties
  inception/pom.xml
Labels: 🐛Bug

#2303 #2302 - Introduce a low-level CAS storage interface
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasMetadataUtils.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageDriver.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageMetadata.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/FileSystemCasStorageDriver.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/config/CasStorageServiceAutoConfiguration.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportCuratedDocumentsTask.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java
  inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java
  inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentImportExportServiceImplTest.java
  inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplConcurrencyTest.java
  inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentsExporterTest.java
  inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporterTest.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
Labels: ⚙️Refactoring

#2305 #2272 - Rename confidence for recommender in the UI
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/log/ActiveLearningRecommendationEventAdapter.java
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/log/ActiveLearningSuggestionOfferedAdapter.java
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception/inception-active-learning/src/main/resources/META-INF/asciidoc/developer-guide/active-learning.adoc
  inception/inception-active-learning/src/main/resources/META-INF/asciidoc/user-guide/annotation_activeLearning.adoc
  inception/inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommender.java
  inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java
  inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Preferences.java
  inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RelationSuggestion.java
  inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SpanSuggestion.java
  inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SuggestionGroup.java
  inception/inception-recommendation-api/src/main/resources/META-INF/asciidoc/developer-guide/implementing_recommender_tutorial.adoc
  inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/model/PredictionGroupTest.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
  inception/inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/recommendation/RecommenderTestHelper.java
Labels: Module: Recommender, ⚙️Refactoring

#2309 #2308 - NullPointerException during indexing
  inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
Labels: Module: Project Search, 🐛Bug

#2284 #2283 Fix Tutorial
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/TutorialFooterPanel.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
Labels: 🐛Bug
