Repository inception-project/inception, pull requests merged in 2021-07, with the labels that each got.

#2432 #1875 - Logout from external authentication
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/PreauthenticationProperties.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/PreauthenticationPropertiesImpl.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityAutoConfiguration.java
  inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-preauth.adoc
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
Labels: 🆕Enhancement

#2437 #2436 - Allow compiling AnnotatorJS as part of Maven build
  inception/inception-html-editor/pom.xml
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlAnnotationEditorImplBase.html
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/annotatorjs/AnnotatorJsHtmlAnnotationEditor.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/annotatorjs/AnnotatorJsRenderer.java
  inception/inception-html-editor/src/main/js/annotatorjs-prebuilt/annotator-full.js
  inception/inception-html-editor/src/main/js/annotatorjs-prebuilt/annotator-full.map
  inception/inception-html-editor/src/main/js/annotatorjs-prebuilt/annotator-full.min.js
  inception/inception-html-editor/src/main/js/annotatorjs-prebuilt/annotator-full.min.map
  inception/inception-html-editor/src/main/js/annotatorjs-prebuilt/annotator.css
  inception/inception-html-editor/src/main/js/annotatorjs-prebuilt/annotator.min.css
  inception/inception-html-editor/src/main/js/annotatorjs/Makefile
  inception/inception-html-editor/src/main/js/annotatorjs/package.json
  inception/inception-html-recogito-editor/pom.xml
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
Labels: Module: HTML, ⚙️Refactoring

#2450 #2448 - PDF does not work anymore due to COEP
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionWebInitializer.java
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/bootstrap.min.css
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/bootstrap.min.js
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/font-awesome.min.css
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/jquery-3.1.1.min.js
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/jquery-ui.css
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/jquery-ui.min.js
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/spectrum.min.css
  inception/inception-pdf-editor/src/main/js/pdfanno/ext/spectrum.min.js
  inception/inception-pdf-editor/src/main/js/pdfanno/gulpfile.js
  inception/inception-pdf-editor/src/main/js/pdfanno/src/index-debug.html
  inception/inception-pdf-editor/src/main/js/pdfanno/src/index.html
Labels: Module: PDF editor, 🐛Bug

#2468 #2461 - NPE when exporting named entities with empty value feature as TEI
  inception/inception-app-webapp/pom.xml
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/TeiFormatSupport.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/backports/TeiWriter.java
Labels: 🐛Bug

#2465 #2463 - Missing commands in Admin docs
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/faq.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
Labels: 📖Documentation

#2387 #2198 - Export and download search queries
  inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception/inception-ui-search/pom.xml
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.properties
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsExporter.java
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProviderWrapper.java
  inception/inception-ui-search/src/test/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsExporterTest.java
Labels: Module: Project Search, 🆕Enhancement

#2427 Refactoring/2423 clean up brat code
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/BratAnnotationLogResourceReference.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/BratUrlMonitorResourceReference.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/ajax.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotation_log.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotator_ui.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/configuration.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/curation_mod.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/dispatcher.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/spinner.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/url_monitor.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/util.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js
Labels: Module: brat, ⚙️Refactoring

#2473 #2472 - Enable minimal internal backups
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/config/BackupProperties.java
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_internal-backup.adoc
Labels: 🆕Enhancement

#2487 #2486 - Remove unused db colums
  inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java
  inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocument.java
  inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
Labels: ⚙️Refactoring

#2474 #2466 - Displayed Text changes as annotations are added / removed
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorProperties.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorPropertiesImpl.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
Labels: Module: brat, 🆕Enhancement

#2494 #2493 - Switch to a JSASS version that runs on Apple Silicon
  inception/inception-ui-core/pom.xml
  inception/pom.xml
Labels: ⚙️Refactoring

#2498 #2497 - Exceptions during task selection and accept best
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
Labels: Module: Recommender, 🐛Bug

#2500 #2499 - Stop bundling MySQL driver
  inception/inception-app-webapp/pom.xml
  inception/pom.xml
Labels: ⚙️Refactoring

#2502 #2493 - Switch to a JSASS version that runs on Apple Silicon
  .gitignore
  inception/inception-support-jsass/pom.xml
  inception/inception-support-jsass/src/main/java/io/bit3/jsass/importer/JsassCustomHeaderImporter.java
  inception/inception-ui-core/pom.xml
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/CustomBootstrapSassReference.java
  inception/pom.xml
Labels: ⚙️Refactoring

#2504 #2503 - Reset admin password
  inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/troubleshooting.adoc
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
Labels: 🆕Enhancement

#2476 Bugfix for #2467 and partially addresses #2442
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
Labels: Module: Project Search, 🐛Bug
