Repository inception-project/inception, pull requests merged in 2022-03, with the labels that each got.

#2874 #898 - Annotators should be able to reopen a finished document
  inception/inception-app-webapp/pom.xml
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationWorkflowActionBarExtension.java
  inception/inception-workload-dynamic/pom.xml
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowActionBarExtension.java
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/trait/DynamicWorkloadTraits.java
  inception/inception-workload-matrix/pom.xml
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarExtension.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.html
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/config/MatrixWorkloadManagerAutoConfiguration.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.properties
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraits.java
  inception/inception-workload-matrix/src/main/resources/META-INF/asciidoc/user-guide/workload_matrix.adoc
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/extension/WorkloadManagerExtension.java
Labels: 🆕Enhancement, Module: Workload

#2877 #2411 - Possibility to reopen documents of an annotator in the curation
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ConfirmationDialog.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxButton.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxEventBehavior.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxFormChoiceComponentUpdatingBehavior.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxFormComponentUpdatingBehavior.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxFormSubmittingBehavior.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxLink.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxSubmitLink.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaButton.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaForm.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaMenuItem.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.html
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.html
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.properties
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
  inception/inception-ui-curation/src/main/resources/META-INF/asciidoc/user-guide/curation.adoc
Labels: 🆕Enhancement, Module: Curation

#2878 #2781 - Upgrade dependencies (23.0)
  inception/inception-pdf-editor/src/main/js/pdfanno/package-lock.json
  inception/inception-pdf-editor/src/main/js/pdfanno/package.json
Labels: ⚙️Refactoring

#2880 #2862 - Multi-value string feature
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeSystemAnalysis.java
  inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeSystemAnalysisTest.java
  inception/inception-api-annotation/src/test/resources/log4j2-test.xml
  inception/inception-api-annotation/src/test/resources/tsd/spanWithArrayFeatures.xml
  inception/inception-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_primitive-features.adoc
Labels: 🆕Enhancement, Module: Project Settings

#2886 #2813 - Recommender calling out to an ELG service
  inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
  inception/inception-imls-elg/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_elg.adoc
Labels: 🆕Enhancement, Module: Recommender, 📖Documentation

#2888 #2781 - Upgrade dependencies
  inception/pom.xml
Labels: ⚙️Refactoring

#2887 #1518 - Document where the settings.properties file lives
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContextInitializer.java
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
Labels: 🆕Enhancement

#2892 #2891 - Predictions are not cleared after deleting the last annotation
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
Labels: 🐛Bug, Module: Recommender

#2895 #2893 - Annotators dropdown in dynamic workload management broken
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.html
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
  inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.properties
Labels: 🐛Bug, Module: Dynamic Workload

#2894 Bugfix/2875 excessive loading times in curation mode
  inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
  inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImpl.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/AnnotatorColumn.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/DocumentMatrixRow.java
  inception/inception-workload-matrix/src/test/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImplTest.java
Labels: 🆕Enhancement, 🚀Performance, Module: Curation, Module: Static Workload

#2896 #2885 - Document java options e.g. for increasing memory limit
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
Labels: 📖Documentation

#2907 #2906 - Allow partial rendering via DIAM AJAX
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LoadAnnotationsHandler.java
  inception/inception-diam/src/main/ts/diam/DiamAjaxImpl.ts
  inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
Labels: 🆕Enhancement, Module: Annotator Web API

#2910 #2393 - Remove outdated project fixings
  inception/inception-api-dao/pom.xml
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/migration/FixAttachFeature330.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/migration/FixCoreferenceFeatures.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/migration/RemoveDanglingFeatures.java
Labels: 💀 Removal

#2909 #2908 - Allow loading only annotations - no text - via DIAM
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RenderRequest.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LoadAnnotationsHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactSerializerImpl.java
  inception/inception-diam/src/main/ts/diam/DiamAjaxImpl.ts
  inception/inception-external-editor/pom.xml
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditor.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/model/AnnotationEditorProperties.java
  inception/inception-html-editor/src/main/ts/annotatorjs/src/plugin/diamstore.ts
  inception/inception-html-recogito-editor/src/main/ts/recogito/RecogitoEditor.ts
  inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
  inception/inception-js-api/src/main/ts/src/editor/AnnotationEditorProperties.ts
Labels: 🆕Enhancement, Module: Annotator Web API

#2913 #2912 - Upgrade dependencies (24.0)
  inception/pom.xml
Labels: ⚙️Refactoring

#2916 #2915 - Sentence layer should not be selectable as recommender target
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
Labels: 🐛Bug, Module: Recommender

#2917 #2781 - Upgrade dependencies (23.0)
  inception/pom.xml
Labels: ⚙️Refactoring

#2919 #2918 - Allow deleting an annotation via DIAM
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/DeleteAnnotationHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/config/DiamAutoConfig.java
  inception/inception-diam/src/main/ts/diam/DiamAjaxImpl.ts
  inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
Labels: 🆕Enhancement, Module: Annotator Web API

#2925 #2924 - Filling in slots via DIAM-based editors does not work
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/DiamAjaxBehavior.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/EditorAjaxRequestHandlerExtensionPointImpl.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint_ImplBase.java
Labels: 🐛Bug, Module: Annotator Web API

#2932 #2931 - Use Maven properties to control some JS dependencies
  inception/inception-brat-editor/src/main/ts_template/package-lock.json
  inception/inception-brat-editor/src/main/ts_template/package.json
  inception/inception-external-editor/src/main/ts_template/package-lock.json
  inception/inception-external-editor/src/main/ts_template/package.json
  inception/inception-html-editor/src/main/ts_template/package-lock.json
  inception/inception-html-editor/src/main/ts_template/package.json
  inception/inception-html-recogito-editor/src/main/ts_template/package.json
  inception/inception-js-api/src/main/ts_template/package-lock.json
  inception/inception-js-api/src/main/ts_template/package.json
  inception/pom.xml
Labels: ⚙️Refactoring
