Repository inception-project/inception, pull requests merged in 2022-02, with the labels that each got.

#2838 #2837 - When marking a sequence in RTL it marks only the last character
  inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
Labels: 🐛Bug, Module: Annotation

#2840 #2839 - Upgrade dependencies
  inception/inception-pdf-editor/pom.xml
  inception/pom.xml
Labels: ⚙️Refactoring

#2845 #878 - Unhide annotation suggestions immediately if an overlapping annotation is deleted
  inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SuggestionGroup.java
  inception/inception-recommendation/pom.xml
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/Fixtures.java
  inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RelationSuggestionVisibilityCalculationTest.java
  inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/SpanSuggestionVisibilityCalculationTest.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
Labels: 🐛Bug, Module: Recommender

#2844 #2735 - Document websocket reverse proxy config
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_home.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_reverse_proxy.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_apache.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_nginx.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_internal-backup.adoc
  inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api.adoc
Labels: 🐛Bug, 📖Documentation

#2843 #2735 - Document websocket reverse proxy config
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_home.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_reverse_proxy.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_apache.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_nginx.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_internal-backup.adoc
  inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api.adoc
Labels: 🐛Bug, 📖Documentation

#2850 #2849 - Arrow heads in relations missing
  .gitignore
  inception/inception-brat-editor/src/main/ts/brat/annotator_ui/AnnotatorUI.ts
  inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
Labels: 🐛Bug, Module: Annotation

#2851 #2686 POS tags and dependency tags are crossing into each other visually
  inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
Labels: 🐛Bug, Module: Annotation, Module: brat

#2856 #2855 - Exclude empty annotations from String Matcher and OpenNLP recommenders
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
  inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
Labels: 🐛Bug, Module: Recommender

#2859 #2829 - Project considered done when first document is curated
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/SourceDocumentStateStats.java
  inception/inception-api/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/SourceDocumentStateStatsTest.java
Labels: 🐛Bug, Module: Workload

#2864 #2861 - Towards multi-value features
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/LinkFeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/StringFeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/UimaPrimitiveFeatureSupport_ImplBase.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ReorderableTagAutoCompleteField.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
  inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
  inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/MultiValueMode.java
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
Labels: ⚙️Refactoring, Module: Annotation

#2866 #2865 - Better info who is writing CAS files and when and why
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateUtils.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageDriver.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/FileSystemCasStorageDriver.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/ConcurentCasModificationException.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/config/RepositoryProperties.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationDocumentService.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationDocumentServiceImpl.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarService.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
Labels: ⚙️Refactoring

#2863 #2862 - Multi-value string feature
  inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalphaunitizing/KrippendorffAlphaUnitizingAgreementMeasure.java
  inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/AbstractCodingAgreementMeasureSupport.java
  inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
  inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementTestUtils.java
  inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaUnitizingAgreementMeasureTest.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/MultiValueStringFeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/MultiSelectTextFeatureEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/MultiSelectTextFeatureEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/MultiValueStringFeatureTraits.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/MultiValueStringFeatureTraitsEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/MultiValueStringFeatureTraitsEditor.java
  inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/MultiValueStringFeatureSupportTest.java
  inception/inception-api-annotation/src/test/resources/desc/type/webannoTestTypes.xml
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/annotationservice/config/AnnotationSchemaServiceAutoConfiguration.java
  inception/inception-curation-legacy/pom.xml
  inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
  inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiffTest.java
  inception/inception-curation-legacy/src/test/resources/desc/type/webannoTestTypes.xml
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommenderFactory.java
  inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ImmutableTag.java
  inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ReorderableTag.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
Labels: 🆕Enhancement, Module: Annotation
