Repository inception-project/inception, pull requests merged in 2022-04, with the labels that each got.

#2936 #2935 - DIAM-based editors not working
  inception/inception-external-editor/pom.xml
  inception/inception-html-editor/pom.xml
  inception/inception-html-recogito-editor/pom.xml
  inception/inception-pdf-editor/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/ServletContextUtils.java
Labels: 🐛Bug, Module: Annotation

#2934 #2933 - Upgrade dependencies
  inception/pom.xml
Labels: ⚙️Refactoring

#2939 #2938 - Pull constraints indicator into a re-usable class
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/exception/WicketExceptionUtil.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ConstraintsInUseIndicator.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/MultiSelectTextFeatureEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextFeatureEditorBase.java
Labels: ⚙️Refactoring, Module: Annotation

#2947 #2946 - PDF editor resources missing from release
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/preferences/BratAnnotationEditorManagerPrefPanel.java
  inception/inception-pdf-editor/pom.xml
Labels: 🐛Bug, Module: PDF editor

#2951 #2948 - Error when dependency layer has been deleted from project
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  inception/inception-brat-editor/pom.xml
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/schema/BratSchemaGeneratorImpl.java
Labels: 🐛Bug, Module: Annotation

#2950 #2943 - Duplicate key error in active learning
  inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoChoiceDescriptionScriptReference.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoComboboxTextFeatureEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.java
  inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ReorderableTag.java
Labels: 🐛Bug, Module: Recommender

#2953 #2952 - Error when trying to locate settings file under Windows
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java
Labels: 🐛Bug

#2954 #2937 - Value shown as 0-1 decimal number instead of 0-100 percentage
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ThresholdBasedMergeStrategyTraitsEditor.java
Labels: 🐛Bug, Module: Curation

#2963 #2962 - Upgrade dependencies
  inception/pom.xml
Labels: ⚙️Refactoring

#2961 #2956 - Workload settings not included in exported projects
  inception/inception-workload/pom.xml
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/config/WorkloadManagementAutoConfiguration.java
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/event/exporter/ExportedWorkloadManager.java
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/event/exporter/WorkloadManagerExporter.java
  inception/inception-workload/src/test/java/de/tudarmstadt/ukp/inception/workload/exporter/WorkloadManagerExporterTest.java
Labels: 🐛Bug, Module: Project Settings

#2965 #2912 - Upgrade dependencies
  inception/pom.xml
Labels: ⚙️Refactoring

#2968 #2967 - Schema validation fails on MySQL 8
  inception/inception-app-webapp/src/main/resources/application.yml
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose-mysql8.yml
Labels: 🐛Bug

#2970 #2969 - Multiple lazy details do not show up properly
  inception/inception-brat-editor/src/main/ts/brat/visualizer_ui/VisualizerUI.ts
Labels: 🐛Bug, Module: Annotation

#2977 #2976 - Add upgrade notes to documentation
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/upgrade_notes.adoc
Labels: 📖Documentation

#2981 #2980 - Cannot open PDF from recent activities
  inception/inception-pdf-editor/pom.xml
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfAnnoPanel.java
Labels: 🐛Bug, Module: PDF editor

#2960 #2957 - Search can't find all tokens of a layer
  inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
  inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
  inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUtils.java
  inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
Labels: 🐛Bug, Module: Project Search

#2984 #2983 - Upgrade dependencies (23.2)
  inception/inception-pdf-editor/src/main/js/pdfanno/package-lock.json
  inception/inception-pdf-editor/src/main/js/pdfanno/package.json
Labels: ⚙️Refactoring

#2985 #2983 - Upgrade dependencies (23.2)
  inception/pom.xml
Labels: ⚙️Refactoring

#2986 #2912 - Upgrade dependencies (24.0)
  inception/pom.xml
Labels: ⚙️Refactoring

#2988 #2987 - Error when pressing "add" when no user is selected
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java
Labels: 🐛Bug, Module: Project Settings

#2991 #2990 - Remove "Javascript action on click" feature
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/config/AnnotationEditorProperties.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerTraitsEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/SpanLayerTraitsEditor.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/annotationservice/config/AnnotationEditorPropertiesImpl.java
Labels: Module: Annotation, Module: Project Settings, 💀 Removal

#2992 #1778 - Make tokenization editable
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/PagingStrategy.java
  inception/inception-api-annotation/src/main/resources/META-INF/asciidoc/user-guide/editable-segmentation.adoc
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/annotationservice/config/AnnotationSchemaServiceAutoConfiguration.java
  inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratSentenceOrientedAnnotationEditorFactory.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationMergeServiceImpl.java
  inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/SentenceLayerInitializer.java
  inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/TokenLayerInitializer.java
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
Labels: 🆕Enhancement, Module: Annotation

#2955 #1893 - Curation does not automatically take stacked annotations
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ThresholdBasedMergeStrategyFactoryImpl.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ThresholdBasedMergeStrategyTraits.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ThresholdBasedMergeStrategyTraitsEditor.html
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ThresholdBasedMergeStrategyTraitsEditor.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/DefaultMergeStrategy.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/MergeIncompleteStrategy.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/MergeStrategy.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/ThresholdBasedMergeStrategy.java
  inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/ThresholdBasedMergeStrategyTest.java
  inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/TokenLayerInitializer.java
  inception/inception-ui-curation/src/main/resources/META-INF/asciidoc/user-guide/curation.adoc
Labels: 🐛Bug, Module: Curation

#2995 #2994 - Merging a slot link does not trigger rendering
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
Labels: 🐛Bug, Module: Curation

#2998 #2997 - Editing PDFs no longer works
  inception/inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderSpan.ts
  inception/inception-pdf-editor/src/main/js/pdfanno/src/core/src/version.ts
Labels: 🐛Bug, Module: PDF editor

#2999 #961 - Relations do not render in Safari for PDF files
  inception/inception-pdf-editor/src/main/js/pdfanno/src/core/index.ts
  inception/inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderRelation.ts
  inception/inception-pdf-editor/src/main/js/pdfanno/src/pdfanno.css
Labels: 🐛Bug, Module: PDF editor, browser-safari

#3002 #3001 - Error when PDF has a blank page inside
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFile.java
  inception/inception-pdf-editor/src/main/js/pdfanno/src/core/index.ts
  inception/inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderRelation.ts
  inception/inception-pdf-editor/src/main/js/pdfanno/src/page/textLayer.ts
  inception/inception-pdf-editor/src/main/js/pdfanno/src/page/util/analyzer.ts
Labels: 🐛Bug, Module: Annotation, Module: PDF editor

#3006 #3005 - Upgrade dependencies (23.3)
  inception/pom.xml
Labels: ⚙️Refactoring

#3004 #2912 - Upgrade dependencies (24.0)
  inception/pom.xml
Labels: ⚙️Refactoring

#3010 #2912 - Upgrade dependencies
  inception/inception-pdf-editor/pom.xml
Labels: ⚙️Refactoring

#3014 #3013 - Application does not start when websocket support is disabled
  inception/inception-diam-editor/pom.xml
  inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/experimental/editor/diamdebugeditor/DiamDebugEditorFactory.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/websocket/ViewportDefinition.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController.java
  inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventFooterPanel.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketController.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketControllerImpl.java
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/config/DashboardAutoConfiguration.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/config/WebsocketAutoConfiguration.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/controller/LoggedEventsWebsocketController.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/controller/LoggedEventsWebsocketControllerImpl.java
  inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/footer/LoggedEventFooterPanel.java
  inception/inception-websocket/src/main/resources/META-INF/asciidoc/admin-guide/settings_websocket.adoc
  inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventsWebsocketControllerImplTest.java
  inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
Labels: 🐛Bug

#3020 #3019 - Telemetry tri-state checkbox broken
  inception/inception-telemetry/pom.xml
  inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetryTraitsEditor.html
  inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetryTraitsEditor.java
  inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/ToggleBox.java
  inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/ToggleBox.properties
  inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/ToggleBox.java
Labels: 🐛Bug

#3023 #3022 - Cannot access AERO swagger UI
  inception/pom.xml
Labels: 🐛Bug, Module: Remote API

#3025 #3024 - Upgrade dependencies (23.4)
  inception/pom.xml
Labels: ⚙️Refactoring

#3027 #3026 - Facilitate running behind reverse proxy
  inception/inception-app-webapp/src/main/resources/application.yml
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_reverse_proxy.adoc
Labels: ⚙️Refactoring

#3015 #3000 - Schema-validation: missing table [annotation_document]
  inception/inception-app-webapp/src/main/resources/application.yml
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mariadb.adoc
Labels: 🐛Bug

#3030 #3029 - Quick project initializer for document labelling tasks
  inception/inception-app-webapp/pom.xml
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionProjectInitializersAutoConfiguration.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicDocumentLabelLayerInitializer.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicDocumentLabelTagSetInitializer.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicDocumentLabelingProjectInitializer.java
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/NamedEntityIdentifierFeatureInitializer.java
Labels: ⚙️Refactoring
