Repository inception-project/inception, pull requests merged in 2022-10, with the labels that each got.

#3409 #3408 - Better documentation of relation queries
  inception/inception-search-mtas/src/main/resources/META-INF/asciidoc/user-guide/search-mtas.adoc
Labels: ⭐️ Enhancement, Module: Project Search, 📖 Documentation

#3410 #3395 - Allow browsing through annotations
  inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
  inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
  inception/inception-diam-editor/src/main/ts/src/SpanText.svelte
  inception/inception-js-api/src/main/ts/src/model/Argument.ts
Labels: ⭐️ Enhancement, Module: Annotation

#3418 Fix typo
  inception/inception-workload/src/main/resources/META-INF/asciidoc/user-guide/workload.adoc
Labels: 📖 Documentation

#3416 #3413 - Support OAuth2 login with browser
  inception/inception-app-webapp/pom.xml
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIOAuth2Handling.java
  inception/inception-app-webapp/src/main/resources/application.yml
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_general.adoc
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
  inception/inception-security/pom.xml
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/OverridableUserDetailsManager.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/LegacyLoginPropertiesImpl.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/LoginProperties.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/LoginPropertiesImpl.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityAutoConfiguration.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
  inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-oauth2.adoc
  inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-preauth.adoc
  inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaBehavior.java
  inception/inception-ui-core/pom.xml
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/OAuth2LoginPanel.html
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/OAuth2LoginPanel.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserDetailPanel.java
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
  inception/pom.xml
Labels: ⭐️ Enhancement

#3420 #3403 - Fix name of ZIP file used for exported XMIs
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/export/ExportDocumentDialogContent.java
  inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporter.java
  inception/inception-documents/pom.xml
  inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
  inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImplTest.java
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/LegacyRemoteApiController.java
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
  inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/AjaxDownloadBehavior.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/AjaxDownloadLink.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/InputStreamResourceStream.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
Labels: 🐛Bug

#3423 #2356 - Reduce exceptions thrown to reduce log pollution
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaMenuItem.java
Labels: ⭐️ Enhancement, Module: Annotation

#3429 #3413 - Support OAuth2 login with browser
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
  inception/inception-app-webapp/pom.xml
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContextInitializer.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIPreAuthenticatedAutoConfiguration.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/cli/UsersCliCommand.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/cli/UsersMigratePreAuthenticatedToRealmCliCommand.java
  inception/inception-curation/suppressions.xml
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/upgrade_notes.adoc
  inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
  inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImplTest.java
  inception/inception-external-search-core/suppressions.xml
  inception/inception-imls-elg/suppressions.xml
  inception/inception-imls-stringmatch/suppressions.xml
  inception/inception-imls-weblicht/suppressions.xml
  inception/inception-kb/suppressions.xml
  inception/inception-log/suppressions.xml
  inception/inception-model/pom.xml
  inception/inception-model/suppressions.xml
  inception/inception-preferences/suppressions.xml
  inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  inception/inception-search-core/suppressions.xml
  inception/inception-security/pom.xml
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/Realm.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/ValidationUtils.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/InceptionSecurityAutoConfiguration.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityAutoConfiguration.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2Adapter.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImpl.java
  inception/inception-security/src/test/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImplTest.java
  inception/inception-security/src/test/java/de/tudarmstadt/ukp/inception/security/oauth/InceptionSecurityWebUIOAuth2HandlingTest.java
  inception/inception-security/suppressions.xml
  inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
  inception/inception-sharing/suppressions.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/db/EmbeddedDatabaseBackupHandler.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/text/TextUtils.java
  inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/text/TextUtilsTest.java
  inception/inception-telemetry/suppressions.xml
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/OAuth2LoginPanel.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/Realm.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserDetailPanel.html
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserDetailPanel.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.java
  inception/inception-workload/suppressions.xml
  inception/pom.xml
Labels: ⭐️ Enhancement

#3434 #2422 - Support editing relations in recogito mode
  inception/inception-bootstrap/src/main/ts_template/package-lock.json
  inception/inception-brat-editor/src/main/ts_template/package-lock.json
  inception/inception-diam/src/main/ts_template/package-lock.json
  inception/inception-external-editor/src/main/ts_template/package-lock.json
  inception/inception-html-editor/src/main/ts/build.js
  inception/inception-html-editor/src/main/ts_template/package-lock.json
  inception/inception-html-recogito-editor/src/main/ts/build.mjs
  inception/inception-html-recogito-editor/src/main/ts/src/main.ts
  inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.css
  inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
  inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditorFactory.ts
  inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
  inception/inception-html-recogito-editor/src/main/ts_template/package.json
  inception/inception-js-api/src/main/ts_template/package-lock.json
  inception/inception-pdf-editor/src/main/ts_template/package-lock.json
  inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
  inception/inception-project-export/src/main/ts_template/package-lock.json
  inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
  inception/inception-ui-kb/src/main/ts_template/package-lock.json
  inception/inception-ui-search/src/main/ts_template/package-lock.json
  inception/pom.xml
Labels: ⭐️ Enhancement, Module: Recogito

#3439 #3438 - External pre-auth broken in INCEpTION 25.0
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java
  inception/inception-security/src/test/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilterTest.java
  inception/inception-security/src/test/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImplTest.java
Labels: 🐛Bug

#3446 #3444 - Add flash message when saving project details
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.html
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java
Labels: ⭐️ Enhancement

#3445 #3443 - Set Cross-Origin-Opener-Policy header
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionServletContextInitializer.java
Labels: ⚙️ Refactoring

#3450 #3448 - Include the INITIAL_CAS in the secondary format
  inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
Labels: ⭐️ Enhancement

#3454 #3451 - HsqlException: user lacks privilege or object not found: maxRecommendations
  inception/inception-recommendation-api/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/model/db-changelog.xml
Labels: 🐛Bug

#3453 #3452 - Enable Spring MVC CSRF protection on UI API and view endpoints
  inception/inception-app-webapp/src/main/resources/META-INF/spring.factories
  inception/inception-diam/pom.xml
  inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
  inception/inception-external-editor/pom.xml
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewController.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlDocumentViewController.java
  inception/inception-html-editor/pom.xml
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentViewController.java
  inception/inception-project-export/pom.xml
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceController.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImpl.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/ProjectExportTask_ImplBase.java
  inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImplTest.java
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityActuatorAutoConfiguration.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityWebUIApiAutoConfiguration.java
  inception/inception-security/src/main/resources/META-INF/spring.factories
  inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletController.java
  inception/inception-websocket/pom.xml
  inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
Labels: ⚙️ Refactoring

#3460 #3459 - Enable CORS on the remote API endpoint
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
Labels: ⚙️ Refactoring, Module: Remote API

#3465 #3464 - Disable external entity handling
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFile.java
Labels: ⚙️ Refactoring

#3467 #3466 - Fix resource leaks
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/PDFExtractor.java
  inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.java
Labels: 🐛Bug

#3469 #3468 - Wrong auto-login property in documentation
  inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-oauth2.adoc
Labels: 🐛Bug, 📖 Documentation

#3472 #3464 - Disable external entity handling
  inception/inception-io-xml/pom.xml
  inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/XmlDocumentReader.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFile.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/XmlParserUtils.java
Labels: ⚙️ Refactoring

#3471 #3470 - Fix string comparison using ==
  inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/Metrics.java
  inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
  inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/StatisticsExporter.java
Labels: 🐛Bug, Module: Project Search

#3473 #3463 - Encode certain characters in log output
  inception/inception-annotation-storage/src/test/resources/log4j2-test.xml
  inception/inception-app-webapp/src/main/resources/log4j2.xml
  inception/inception-concept-linking/src/test/resources/log4j2-test.xml
  inception/inception-constraints/src/test/resources/log4j2-test.xml
  inception/inception-curation-legacy/src/test/resources/log4j2-test.xml
  inception/inception-documents/src/test/resources/log4j2-test.xml
  inception/inception-example-imls-data-majority/src/test/resources/log4j2-test.xml
  inception/inception-external-search-solr/src/test/resources/log4j2-test.xml
  inception/inception-imls-dl4j/src/test/resources/log4j2-test.xml
  inception/inception-imls-opennlp/src/test/resources/log4j2-test.xml
  inception/inception-imls-stringmatch/src/test/resources/log4j2-test.xml
  inception/inception-io-html/src/test/resources/log4j2-test.xml
  inception/inception-io-webanno-tsv/src/test/resources/log4j.properties
  inception/inception-io-webanno-tsv/src/test/resources/log4j2-test.xml
  inception/inception-kb/src/test/resources/log4j2-test.xml
  inception/inception-log/src/test/resources/log4j2-test.xml
  inception/inception-project-export/src/test/resources/log4j2-test.xml
  inception/inception-remote/src/test/resources/log4j2-test.xml
  inception/inception-search-core/src/test/resources/log4j2-test.xml
  inception/inception-search-mtas/src/test/resources/log4j2-test.xml
  inception/inception-versioning/src/test/resources/log4j2-test.xml
  inception/inception-workload-dynamic/src/test/resources/log4j2-test.xml
Labels: ⚙️ Refactoring

#3475 #3431 - Update dependencies
  inception/pom.xml
Labels: ⚙️ Refactoring

#3477 #3476 - Update dependencies (25.2)
  inception/inception-bootstrap/src/main/ts_template/package-lock.json
  inception/inception-brat-editor/src/main/ts_template/package-lock.json
  inception/inception-diam-editor/src/main/ts_template/package-lock.json
  inception/inception-diam/src/main/ts_template/package-lock.json
  inception/inception-external-editor/src/main/ts_template/package-lock.json
  inception/inception-html-editor/src/main/ts_template/package-lock.json
  inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
  inception/inception-js-api/src/main/ts_template/package-lock.json
  inception/inception-kb/pom.xml
  inception/inception-pdf-editor/src/main/ts_template/package-lock.json
  inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
  inception/inception-project-export/src/main/ts_template/package-lock.json
  inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
  inception/inception-ui-kb/src/main/ts_template/package-lock.json
  inception/inception-ui-search/src/main/ts_template/package-lock.json
  inception/pom.xml
  inception/update-package-lock.sh
Labels: ⚙️ Refactoring

#3482 #3481 - Improve short project descriptions in project overview
  inception/inception-sharing/pom.xml
  inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
  inception/inception-support/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/DescriptionTooltipBehavior.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/MarkdownUtil.java
  inception/inception-ui-dashboard/pom.xml
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.java
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectEntry.java
  inception/inception-ui-kb/pom.xml
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseInfoPanel.java
  inception/pom.xml
Labels: ⭐️ Enhancement, Module: Dashboard

#3480 #3479 - Demote HTML-editor support to experimental status
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlCas2SaxEvents.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/config/HtmlAnnotationEditorSupportAutoConfiguration.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentRenderer.java
  inception/inception-io-conll/pom.xml
  inception/inception-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/config/ConllFormatsAutoConfiguration.java
  inception/inception-io-html/pom.xml
  inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/HtmlFormatSupport.java
  inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/config/HtmlSupportAutoConfiguration.java
  inception/inception-io-html/src/main/resources/META-INF/spring.factories
  inception/inception-io-imscwb/pom.xml
  inception/inception-io-imscwb/src/main/java/de/tudarmstadt/ukp/inception/io/imscwb/ImsCwbFormatSupport.java
  inception/inception-io-imscwb/src/main/java/de/tudarmstadt/ukp/inception/io/imscwb/config/ImsCwbFormatSupportAutoConfiguration.java
  inception/inception-io-imscwb/src/main/resources/META-INF/spring.factories
  inception/inception-io-lif/pom.xml
  inception/inception-io-lif/src/main/java/de/tudarmstadt/ukp/inception/io/lif/LifFormatSupport.java
  inception/inception-io-lif/src/main/java/de/tudarmstadt/ukp/inception/io/lif/config/LifFormatSupportAutoConfiguration.java
  inception/inception-io-lif/src/main/resources/META-INF/spring.factories
  inception/inception-io-nif/pom.xml
  inception/inception-io-nif/src/main/java/de/tudarmstadt/ukp/inception/io/nif/NifFormatSupport.java
  inception/inception-io-nif/src/main/java/de/tudarmstadt/ukp/inception/io/nif/config/NifFormatSupportAutoConfiguration.java
  inception/inception-io-nif/src/main/resources/META-INF/spring.factories
  inception/inception-io-perseus/pom.xml
  inception/inception-io-perseus/src/main/java/de/tudarmstadt/ukp/inception/io/perseus/PerseusFormatSupport.java
  inception/inception-io-perseus/src/main/java/de/tudarmstadt/ukp/inception/io/perseus/config/PerseusFormatAutoConfiguration.java
  inception/inception-io-perseus/src/main/resources/META-INF/spring.factories
  inception/inception-io-tcf/pom.xml
  inception/inception-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfFormatSupport.java
  inception/inception-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/config/TcfFormatsAutoConfiguration.java
  inception/inception-io-tcf/src/main/resources/META-INF/spring.factories
  inception/inception-io-tei/pom.xml
  inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiFormatSupport.java
  inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/config/TeiFormatsAutoConfiguration.java
  inception/inception-io-tei/src/main/resources/META-INF/spring.factories
  inception/inception-io-text/pom.xml
  inception/inception-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/config/TextFormatsAutoConfiguration.java
  inception/inception-io-webanno-tsv/pom.xml
  inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv1FormatSupport.java
  inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv2FormatSupport.java
  inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3FormatSupport.java
  inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/config/WebAnnoFormatsAutoConfiguration.java
  inception/inception-io-webanno-tsv/src/main/resources/META-INF/spring.factories
  inception/inception-io-xml/pom.xml
  inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/config/XmlSupportAutoConfiguration.java
  inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/XmlDocumentWriter.java
  inception/inception-support/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/XmlParserUtils.java
Labels: ⚙️ Refactoring, Module: AnnotatorJS

#3483 #3463 - Encode certain characters in log output
  inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupportRegistryImpl.java
  inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImpl.java
  inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/driver/filesystem/FileSystemCasStorageDriver.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/behaviors/LayerBehaviorRegistryImpl.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/behaviors/LayerSupportRegistryImpl.java
  inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorExtensionRegistryImpl.java
  inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorRegistryImpl.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContextInitializer.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIPreAuthenticatedAutoConfiguration.java
  inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/cli/UsersMigratePreAuthenticatedToRealmCliCommand.java
  inception/inception-app-webapp/src/main/resources/log4j2.xml
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/util/FileUtils.java
  inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
  inception/inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchProviderRegistryImpl.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/EventLoggingAdapterRegistryImpl.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
  inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommenderFactoryRegistryImpl.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Annotation_Test.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Authentication_PreAuth_Test.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Authentication_Test.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Curation_Test.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Document_Test.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Permissions_Test.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_ProjectExport_Test.java
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Project_Test.java
  inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/FeatureIndexingSupportRegistryImpl.java
  inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
  inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndexRegistryImpl.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/InceptionSecurityAutoConfiguration.java
  inception/inception-security/src/test/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilterTest.java
  inception/inception-security/src/test/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImplTest.java
  inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java
  inception/inception-support/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint_ImplBase.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/interceptors/GlobalInterceptorsRegistryImpl.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/logging/BaseLoggers.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/logging/RingBufferAppender.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/deployment/DeploymentMode.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/deployment/DeploymentModeService.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/deployment/DeploymentModeServiceImpl.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/spring/DatabaseInfoService.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/spring/StartupWatcher.java
  inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryService.java
  inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryServiceImpl.java
  inception/inception-telemetry/src/test/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImplTest.java
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebarRegistryImpl.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/footer/FooterItemRegistryImpl.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItemRegistryImpl.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/settings/ProjectSettingsPanelRegistryImpl.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/coloring/StatementColoringRegistryImpl.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/ValueTypeSupportRegistryImpl.java
  inception/pom.xml
Labels: ⚙️ Refactoring

#3484 #3476 - Update dependencies (25.2)
  inception/inception-brat-editor/src/main/ts_template/package-lock.json
  inception/inception-diam-editor/src/main/ts_template/package-lock.json
  inception/inception-diam/src/main/ts_template/package-lock.json
  inception/inception-external-editor/src/main/ts_template/package-lock.json
  inception/inception-html-editor/src/main/ts_template/package-lock.json
  inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
  inception/inception-js-api/src/main/ts_template/package-lock.json
  inception/inception-pdf-editor/src/main/ts_template/package-lock.json
  inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
  inception/inception-project-export/src/main/ts_template/package-lock.json
  inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
  inception/pom.xml
Labels: ⚙️ Refactoring

#3497 #3495 - Configurable editor content policies
  inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
  inception/inception-external-editor/pom.xml
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditorFactory.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/XmlDocumentViewControllerImplBase.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorAutoConfiguration.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorLoader.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorPluginDescripion.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorProperties.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorPropertiesImpl.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/SafetyNetDocumentPolicy.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlDocumentViewControllerImpl.java
  inception/inception-external-editor/src/main/resources/META-INF/asciidoc/developer-guide/external-editor.adoc
  inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicyTest.java
  inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/SafetyNetDocumentPolicyTest.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/config/HtmlAnnotationEditorSupportAutoConfiguration.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentIFrameView.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentIFrameViewFactory.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentRenderer.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentView.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentViewController.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentViewControllerImpl.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentViewFactory.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/LegacyHtmlDocumentRenderer.java
  inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/config/XmlSupportAutoConfiguration.java
  inception/inception-support/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/WatchedResourceFile.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/YamlUtil.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/xml/ContentHandlerAdapter.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/XmlParserUtils.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/AttributeAction.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/AttributePolicy.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/AttributePolicyBuilder.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/DelegatingAttributePolicy.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ElementAction.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ElementPolicy.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ElementPolicyBuilder.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ExternalPolicy.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ExternalPolicyCollection.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PatternAttributePolicy.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollection.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionBuilder.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtils.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
  inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtilsTest.java
  inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionTest.java
  inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandlerTest.java
  inception/inception-support/src/test/resources/SanitizingContentHandler/EmptyPolicy.yaml
  inception/inception-support/src/test/resources/SanitizingContentHandler/Policy.yaml
  inception/inception-support/src/test/resources/log4j2-test.xml
Labels: ⭐️ Enhancement, Module: Annotation

#3498 #3496 - Update dependencies
  inception/pom.xml
Labels: ⚙️ Refactoring

#3499 #3462 - "Required" greyed out but NOT checked for integer features
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/bool/BooleanFeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureTraits.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureTraitsEditor.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraits.java
  inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/feature/FeatureSupport.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/JSONUtil.java
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
Labels: 🐛Bug, Module: Project Settings

#3501 #3500 - Lazy details do not show anymore in brat editor
  inception/inception-brat-editor/src/main/ts/src/BratEditor.ts
  inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
  inception/inception-brat-editor/src/main/ts/src/visualizer_ui/VisualizerUI.ts
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/EditorAjaxRequestHandlerBase.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LazyDetailsHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LoadAnnotationsHandler.java
  inception/inception-diam/src/main/ts/src/diam/DiamAjaxImpl.ts
  inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
Labels: 🐛Bug, Module: brat

#3503 #3502 - Combo-box and auto-complete field dropdown layout is broken
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiSelectTextFeatureEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoAutoCompleteTextFeatureEditor.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoChoiceDescriptionScriptReference.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoComboboxTextFeatureEditor.html
  inception/inception-bootstrap/src/main/ts/bootstrap/shim-kendo.scss
Labels: 🐛Bug, Module: Annotation

#3504 #3494 - Display of label description when hovering over the label
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
  inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/feature/FeatureSupport.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
  inception/inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureSupport.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
Labels: ⭐️ Enhancement, Module: Annotation, Module: brat

#3505 #3492 - Deleting a layer feature doesn't always work
  inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
Labels: 🐛Bug, Module: Project Settings

#3507 #3506 - No sessions should be created when remote API is accessed
  inception/inception-app-webapp/src/main/resources/application.yml
Labels: 🐛Bug

#3509 #3508 - OAuth2 login to remote API
  inception/inception-remote/pom.xml
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/RemoteApiProperties.java
  inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api.adoc
  inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Authentication_Jwt_Test.java
  inception/inception-security/pom.xml
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2Adapter.java
  inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImpl.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.java
  inception/pom.xml
Labels: ⭐️ Enhancement, Module: Remote API

#3510 #3495 - Configurable editor content policies
  inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditorFactory.java
  inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.java
  inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicyTest.java
  inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/SafetyNetDocumentPolicyTest.java
  inception/inception-external-editor/src/test/resources/log4j2-test.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/WatchedResourceFile.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
Labels: ⭐️ Enhancement, Module: Annotation
