Repository inception-project/inception, pull requests merged in 2022-05, with the labels that each got.

#3032 #3031 - setFeatureValue logic should be directly in feature supports
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
Labels: ⚙️Refactoring, Module: Annotation

#3028 #3003 - Clean up PDF editor code
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfDocumentIFrameView.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFile.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/DrawOperator.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/ImageOperator.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/Operator.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/PDFExtractor.java
  inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/TextOperator.java
  inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/UI/span.ts
  inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/UI/utils.ts
  inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/annotation/relation.ts
  inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/annotation/span.ts
  inception/inception-pdf-editor/src/main/ts/src/pdfanno/page/textLayer.ts
  inception/inception-pdf-editor/src/main/ts/src/pdfanno/page/util/analyzer.ts
  inception/inception-pdf-editor/src/test/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfAnnoModelTest.java
  inception/inception-pdf-editor/src/test/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
  inception/inception-pdf-editor/src/test/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFileTest.java
Labels: ⚙️Refactoring

#3041 #3040 - Drop JSASS
  inception/inception-support-jsass/pom.xml
  inception/inception-support-jsass/src/main/java/io/bit3/jsass/importer/JsassCustomHeaderImporter.java
  inception/inception-ui-core/pom.xml
Labels: 💀 Removal

#3042 #3034 - NumberFeatureTraits should ignore unknown traits
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureTraits.java
Labels: 🐛Bug, Module: Project Settings

#3047 #3046 - Upgrade dependencies
  inception/pom.xml
Labels: ⚙️Refactoring

#3050 #3049 - Can add empty IRI as additional property
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AdditionalMatchingPropertiesPanel.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/RootConceptsPanel.java
Labels: 🐛Bug, Module: Knowledge Base

#3051 #3035 - Document caddy
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mariadb.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_reverse_proxy.adoc
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_caddy.adoc
Labels: 📖Documentation

#3053 #3052 - Cannot export project when websocket is disabled
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/ProjectExportTask_ImplBase.java
Labels: 🐛Bug, Module: Project Settings

#3056 #3055 - Some logged events to not contain document/project information
  inception/inception-layer-docmetadata/pom.xml
  inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/log/DocumentMetadataEventAdapter.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/BulkAnnotationEventAdapter.java
Labels: 🐛Bug, Module: Logging

#3058 #3057 - Exception in activities dashlet
  inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletControllerImpl.java
Labels: 🐛Bug, Module: Dashboard

#3068 #3067 - KB still used even when disabled
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
  inception/inception-kb-fact-linking/src/main/java/de/tudarmstadt/ukp/inception/kb/factlinking/feature/FactLinkingServiceImpl.java
  inception/inception-kb-fact-linking/src/main/java/de/tudarmstadt/ukp/inception/kb/factlinking/feature/PropertyFeatureSupport.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePageMenuItem.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
Labels: 🐛Bug, Module: Knowledge Base

#3060 #3059 - Add support for the Stardog SPARQL FTS service
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/IriConstants.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/StardogEntitySearchService.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FusekiRepositoryTest.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/Rdf4JRepositoryTest.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/StardogRepositoryTest.java
  inception/inception-kb/src/test/resources/data/wordnet-ontolex-ontology.owl
  inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/projects_knowledge-base.adoc
Labels: 🆕Enhancement, Module: Knowledge Base

#3065 #3064 - Refactor KB tests
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FusekiRepositoryTest.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/Rdf4JRepositoryTest.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/RepositoryTestSuite.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/StardogRepositoryTest.java
  inception/pom.xml
Labels: 🐛Bug, Module: Knowledge Base, ⚙️Refactoring

#3074 #3073 - Upgrade dependencies (23.6)
  inception/pom.xml
Labels: ⚙️Refactoring

#3075 #3038 - Search on large local knowledge base is much slower than expected
  inception/inception-concept-linking/pom.xml
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
  inception/inception-kb/NOTICE.txt
  inception/inception-kb/pom.xml
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/ExportedKnowledgeBase.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/model/KnowledgeBase.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryPrimaryConditions.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/backport/Bind.java
  inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/model/db-changelog.xml
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/QuerySettingsPanel.html
  inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/QuerySettingsPanel.java
  inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/projects_knowledge-base.adoc
Labels: 🐛Bug, Module: Knowledge Base

#3077 #3076 - Items matching text entered in to concept feature editor often appear late
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/config/EntityLinkingServiceAutoConfiguration.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/CasingFeatureGenerator.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/LevenshteinFeatureGenerator.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/model/CandidateEntity.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java
  inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
  inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategyTest.java
  inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImplTest.java
Labels: 🐛Bug, Module: Knowledge Base, Module: Entity Linking

#3078 #3063 - Add "create missing users" option to project import AERO endpoint
  inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
Labels: 🆕Enhancement, Module: Remote API

#3045 #3044 - Also show NPM dependencies on third-party dependency report on about page
  NOTICE.txt
  inception/inception-bootstrap/src/main/ts_template/package.json
  inception/inception-brat-editor/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
  inception/inception-brat-editor/src/main/ts_template/package.json
  inception/inception-build/src/main/resources/inception/licenseCheckerCustomFormat.json
  inception/inception-diam/src/main/ts_template/package.json
  inception/inception-external-editor/NOTICE.txt
  inception/inception-external-editor/src/main/ts_template/package.json
  inception/inception-html-editor/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
  inception/inception-html-editor/src/main/ts/build.js
  inception/inception-html-editor/src/main/ts_template/package-lock.json
  inception/inception-html-editor/src/main/ts_template/package.json
  inception/inception-html-recogito-editor/NOTICE.txt
  inception/inception-html-recogito-editor/src/main/ts_template/package.json
  inception/inception-imls-stringmatch/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
  inception/inception-io-json/NOTICE.txt
  inception/inception-js-api/pom.xml
  inception/inception-js-api/src/main/ts_template/package.json
  inception/inception-kb/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
  inception/inception-pdf-editor/NOTICE.txt
  inception/inception-pdf-editor/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
  inception/inception-pdf-editor/src/main/ts_template/package.json
  inception/inception-support/NOTICE.txt
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/AbstractDependency.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/ApplicationInformation.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/Dependency.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/EmbeddedSpdxDependencies.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/MavenDependencies.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/MavenDependency.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/MavenLicense.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/NpmDependencies.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/NpmDependency.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/about/SpdxPackage.java
  inception/inception-support/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
  inception/inception-support/src/test/java/de/tudarmstadt/ukp/clarin/webanno/support/about/ApplicationInformationTest.java
  inception/inception-support/src/test/resources/ApplicationInformationTest/DEPENDENCIES.json
  inception/inception-support/src/test/resources/ApplicationInformationTest/NPM-DEPENDENCIES.json
  inception/inception-ui-core/NOTICE.txt
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/about/AboutPage.java
  inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/about/AboutPage.properties
  inception/inception-ui-core/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
  inception/inception-ui-kb/src/main/ts_template/package.json
  inception/inception-ui-search/src/main/ts_template/package.json
  inception/pom.xml
  pom.xml
Labels: 🆕Enhancement

#3081 #3080 - Token "morph" feature has wrong type
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/LayerExporter.java
  inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
  inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/MorphologicalFeaturesLayerInitializer.java
  inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
Labels: 🐛Bug, Module: Project Settings

#3086 #2881 - Document Deletion not working
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceEventAdapter.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/annotationservice/config/AnnotationSchemaServiceAutoConfiguration.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/AfterProjectRemovedEvent.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AfterProjectRemovedEventAdapter.java
  inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
  inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java
  inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
  inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
Labels: 🐛Bug

#3087 #3079 - Remove UrlParametersReceivingBehavior if possible
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
  inception/inception-support/NOTICE.txt
  inception/inception-support/pom.xml
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicketstuff/UrlParametersReceivingBehavior.java
  inception/inception-support/src/main/resources/META-INF/DEPENDENCIES-EMBEDDED.spdx.json
Labels: ⚙️Refactoring
