Repository inception-project/inception, pull requests merged in 2023-06, with the labels that each got.

#4049 #4048 - Document navigation options not visible to manager when viewing other users document
  inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentAccess.java
  inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentAccessImpl.java
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/docnav/DocumentNavigator.java
  inception/inception-ui-curation/pom.xml
  inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationDocumentNavigator.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowDocumentNavigationActionBarExtension.java
  inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/config/MatrixWorkloadManagerAutoConfiguration.java
Labels: 🐛Bug, Module: Annotation, Module: Curation

#4053 #4052 - Admins no longer see all projects in the project overview
  inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
Labels: 🐛Bug, Module: Dashboard

#4056 #4055 - Editor scrolls up when left sidebar is opened/closed
  inception/inception-brat-editor/src/main/ts/src/BratEditor.ts
  inception/inception-brat-editor/src/main/ts/src/visualizer_ui/VisualizerUI.ts
  inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTabbedPanel.java
Labels: 🐛Bug, Module: Annotation

#4057 update dead link to the new file
  inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/logging.adoc
Labels: 🐛Bug, 📖 Documentation

#4059 #4026: Support for error tracking with Sentry
  inception/inception-app-webapp/pom.xml
  inception/pom.xml
Labels: ⭐️ Enhancement

#4061 #4060 - Clean up redundant code in annotation handlers
  inception/inception-diam/pom.xml
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithExistingAnnotationHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithNewAnnotationHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/MoveSpanAnnotationHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ScrollToHandler.java
  inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/wicket-package.properties
  inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandlerTest.java
  inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/annotatorjs/AnnotatorJsHtmlAnnotationEditor.java
  inception/pom.xml
Labels: ⚙️ Refactoring, Module: Annotation

#4063 #4062 - ViewportTracker should focus on block-like elements
  inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
Labels: ⚙️ Refactoring, Module: JavaScript Editor API

#4067 #4066 - Display document name on export failure
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
  inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExporter.java
  inception/inception-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/export/ConstraintsExporter.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporter.java
  inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CurationWorkflowExporter.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectSettingsExporter.java
  inception/inception-guidelines/src/main/java/de/tudarmstadt/ukp/inception/guidelines/exporters/GuidelinesExporter.java
  inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/gazeteer/exporter/GazeteerExporter.java
  inception/inception-imls-weblicht/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/weblicht/exporter/ChainExporter.java
  inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
  inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/ProjectExportTask_ImplBase.java
  inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/exporters/ProjectPermissionsExporter.java
  inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java
  inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/LayerExporter.java
  inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/TagSetExporter.java
  inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/exporters/ProjectInviteExporter.java
  inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/event/exporter/WorkloadManagerExporter.java
Labels: ⭐️ Enhancement

#4070 #3673 - Update dependencies
  inception/inception-io-html/src/test/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/HtmlDocumentReaderTest.java
  inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
  inception/pom.xml
Labels: ⚙️ Refactoring

#4065 #4058 - Cannot export texts containing certain characters as UIMA CAS XMI
  inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporterTest.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
  inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/config/DocumentImportExportServiceAutoConfiguration.java
  inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImplTest.java
  inception/inception-io-xmi/pom.xml
  inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/BinaryCasFormatSupport.java
  inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/UimaInlineXmlFormatSupport.java
  inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/XmiFormatSupport.java
  inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/XmiXml11FormatSupport.java
  inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/config/UimaFormatsAutoConfiguration.java
  inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/config/UimaFormatsProperties.java
  inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/config/UimaFormatsPropertiesImpl.java
  inception/inception-io-xmi/src/main/resources/META-INF/asciidoc/user-guide/formats-uimaxmi.adoc
  inception/inception-io-xmi/src/main/resources/META-INF/spring.factories
  inception/inception-io-xmi/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  inception/inception-io-xml/src/main/resources/desc/type/XmlStructure.xml
  inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/curated/CuratedDocumentsProjectExporterPanel.java
  inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/AnnotationDocumentsExporterTest.java
  inception/inception-search-mtas/pom.xml
  inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
  inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUpgradeTest.java
  inception/inception-versioning/src/test/java/de/tudarmstadt/ukp/inception/versioning/VersioningServiceImplTest.java
Labels: 🐛Bug

#4077 #4074 - Text color does not change depending on background color in color rule editor
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.java
  inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/Coloring.java
Labels: 🐛Bug, Module: Project Settings

#4078 #4075 - Re-ordering of coloring rules
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.html
  inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.java
Labels: ⭐️ Enhancement, Module: Project Settings
